// Generated by OpenFlex Neo
// AS4 -> JavaScript

async function initializeStore() {
  console.log("🛒 OpenFlex E-Commerce Store");
);
  sole.lo.("I(itializing...");
);
  await unknown();
  let en =  = AuthToken();();
  if (en) {) {
    sole.lo.("✓(User session restored");
  );
  }
  return;
}

alizeStore().th().() =(() => {
  le.log(.Don(!");
}));
}).((err() =>  => {
  le.erro.("Err(r:", err, );
}));
});
