// Generated by OpenFlex Neo
// AS4 -> JavaScript


// Polyfill for Node.js
const trace = typeof console !== 'undefined' ? console.log : () => {};
class Animal {
  name;
  age;
  makeSound() {
    return "Some generic sound";
  }
  describe() {
    return name + " is " + age + " years old";
  }
}

class Dog extends Animal {
  breed;
  makeSound() {
    return "Woof!";
  }
  fetch() {
    return name + " is fetching the ball!";
  }
}

function greet(name = "World", greeting = "Hello") {
  return greeting + ", " + name + "!";
}

function createUser(name, age = 18, active = true) {
  return "User: " + name + ", Age: " + age + ", Active: " + active;
}

function calculateGrade(score) {
  if (score >= 90) {
    return "A";
  }
  else   if (score >= 80) {
    return "B";
  }
  else   if (score >= 70) {
    return "C";
  }
  else   if (score >= 60) {
    return "D";
  }
  else {
    return "F";
  }
}

function fibonacci(n) {
  if (n <= 1) {
    return n;
  }
  let a = 0;
  let b = 1;
  let temp = 0;
  for (let i = 2; i <= n; i++) {
    temp = a + b;
    a = b;
    b = temp;
  }
  return b;
}

function countdown(from) {
  while (from > 0) {
    trace(from);
    from = from - 1;
  }
}

class Calculator {
  memory;
  add(a, b = 0) {
    return a + b;
  }
  multiply(a, b = 1) {
    return a * b;
  }
  power(base, exponent = 2) {
    let result = 1;
    for (let i = 0; i < exponent; i++) {
      result = result * base;
    }
    return result;
  }
  storeInMemory(value) {
    memory = value;
  }
  recall() {
    return memory;
  }
}

trace("=== Advanced OpenFlex Neo Demo ===");

trace("");

trace("--- Default Parameters ---");

trace(greet());

trace(greet("Alice"));

trace(greet("Bob", "Hi"));

trace(createUser("Charlie"));

trace(createUser("Diana", 25));

trace(createUser("Eve", 30, false));

trace("");

trace("--- Classes & Inheritance ---");

trace("Dog Buddy says: Woof!");

trace("Buddy is 3 years old");

trace("Buddy is fetching the ball!");

trace("");

trace("--- Control Flow ---");

trace("Score 95: Grade " + calculateGrade(95));

trace("Score 85: Grade " + calculateGrade(85));

trace("Score 75: Grade " + calculateGrade(75));

trace("Score 65: Grade " + calculateGrade(65));

trace("Score 55: Grade " + calculateGrade(55));

trace("");

trace("--- Advanced Algorithms ---");

trace("Fibonacci(0) = " + fibonacci(0));

trace("Fibonacci(1) = " + fibonacci(1));

trace("Fibonacci(5) = " + fibonacci(5));

trace("Fibonacci(10) = " + fibonacci(10));

trace("");

trace("--- Calculator Demo ---");

trace("5 + 3 = 8");

trace("5 * 3 = 15");

trace("2^3 = 8");

trace("2^5 = 32");

trace("");

trace("✨ All features working perfectly! ✨");
