// Generated by OpenFlex Neo
// AS4 -> JavaScript

[first, second, third] = [1, 2, 3];

trace("first:", first);

trace("second:", second);

trace("third:", third);

[a, c] = [10, 20, 30];

trace("a:", a);

trace("c:", c);

[head] = [1, 2, 3, 4, 5];

trace("head:", head);

trace("tail:", tail);

trace("tail length:", tail.length);

[[x1, y1], [x2, y2]] = [[10, 20], [30, 40]];

trace("Point 1:", x1, y1);

trace("Point 2:", x2, y2);

function getCoordinates() {
  return [42, 17];
}

[x, y] = getCoordinates();

trace("Coordinates:", x, y);

let = 10;

let = 20;

[m, n] = [n, m];

trace("After swap - m:", m, "n:", n);

const person = { name: "Alice", age: 30, city: "NYC" };

const city = person;

trace("Name:", name);

trace("Age:", age);

trace("City:", city);

{ name: personName, age: personAge } = person;

trace("Person name:", personName);

trace("Person age:", personAge);

const user = { id: 123, profile: { username: "alice", email: "alice@example.com" }, settings: { theme: "dark", notifications: true } };

const profile = user;

trace("ID:", id);

trace("Username:", username);

trace("Email:", email);

trace("Theme:", theme);

const point = { x: 10, y: 20, z: 30, label: "Point A" };

{ x: px, y: py } = point;

trace("Position:", px, py);

trace("Metadata:", metadata);

const users = [{ name: "Bob", score: 85 }, { name: "Carol", score: 92 }, { name: "Dave", score: 78 }];

[{ name: winner, score: winnerScore }] = users;

trace("Winner:", winner, "with score", winnerScore);

const data = { coordinates: [100, 200], label: "Origin", colors: ["red", "green", "blue"] };

{ coordinates: [cx, cy], label: dataLabel, colors: [primary] } = data;

trace("Coordinates:", cx, cy);

trace("Label:", dataLabel);

trace("Primary color:", primary);

trace("Other colors:", otherColors);

async function fetchUser(userId) {
  let response = await fetch("/api/users/" + userId);
  let error = await response.json();
  if (status = "success") {
    return data;
  }
  else {}
}

const defaultConfig = { timeout: 5000, retries: 3, debug: false, endpoint: "/api" };

function makeRequest(options) {
  let config = {};
  let endpoint = config;
  trace("Request config:");
  trace("  Endpoint:", endpoint);
  trace("  Timeout:", timeout);
  trace("  Retries:", retries);
  trace("  Debug:", debug);
}

makeRequest({ endpoint: "/api/users", debug: true });

function getStats() {
  return { mean: 42.5, median: 40, mode: 38, stdDev: 5.2 };
}

const stdDev = getStats();

trace("Statistics:");

trace("  Mean:", mean);

trace("  Median:", median);

trace("  Std Dev:", stdDev);

const apiResponse = { status: 200, body: { user: { id: 456, profile: { name: "Eve", preferences: { language: "en", timezone: "UTC" } } }, metadata: { timestamp: 1234567890, version: "2.0" } } };

{ status: httpStatus, body: { user: { profile: { name: userName, preferences: {} } }, metadata: {} } } = apiResponse;

trace("HTTP Status:", httpStatus);

trace("User:", userName);

trace("Language:", language);

trace("Timezone:", timezone);

trace("API Version:", version);

const points = [[10, 20], [30, 40], [50, 60]];

trace("Points:");

for (let i = 0; i < points.length; i++) {
  [px, py] = points[i];
  trace("  Point " + i + ": (" + px + ", " + py + ")");
}

let;

{ timeout: config } = { timeout: 3000 };

trace("Config timeout:", config);

const matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]];

[[r1c1, r1c2, r1c3], [r2c1, r2c2, r2c3], [r3c1, r3c2, r3c3]] = matrix;

trace("Matrix center:", r2c2);

const fullData = { id: 1, name: "Test", description: "A test object", created: "2024-01-01", modified: "2024-01-02", metadata: { tags: ["test", "demo"], priority: "high" } };

{ id: dataId, name: dataName, metadata: {} } = fullData;

trace("ID:", dataId);

trace("Name:", dataName);

trace("Tags:", tags);

function runDemo() {
  trace("=== Destructuring Demo Complete ===");
  trace("");
  trace("Demonstrated:");
  trace("  ✓ Array destructuring with rest elements"););
  ace("( ✓ Object destructuring with renaming");
 );
  e("  ( Nested destructuring patterns");
   );
  "  ✓ (ixed array and object destructuring");
    t);
   ✓ Re(l-world examples with async/await");
    tra);
   Deep(y nested data extraction");
}

runDem);
}

();
