// Generated by OpenFlex Neo - Destructuring Demo (Simplified)
// AS4 -> JavaScript

// Polyfill for Node.js
const trace = typeof console !== 'undefined' ? console.log : () => {};

trace("=== Destructuring Demo ===");
trace("");

// Array Destructuring
trace("--- Array Destructuring ---");
const numbers = [1, 2, 3, 4, 5];
const [first, second, ...rest] = numbers;
trace("First:", first);
trace("Second:", second);
trace("Rest:", rest);
trace("");

// Object Destructuring
trace("--- Object Destructuring ---");
const person = { name: "Alice", age: 30, city: "Paris" };
const { name, age, city } = person;
trace("Name:", name);
trace("Age:", age);
trace("City:", city);
trace("");

// Nested Destructuring
trace("--- Nested Destructuring ---");
const user = {
    id: 1,
    profile: {
        username: "alice123",
        email: "alice@example.com"
    }
};
const { profile: { username, email } } = user;
trace("Username:", username);
trace("Email:", email);
trace("");

// With Defaults
trace("--- With Default Values ---");
const options = { timeout: 3000 };
const { timeout = 5000, retries = 3 } = options;
trace("Timeout:", timeout);
trace("Retries:", retries);
