// Generated by OpenFlex Neo
// AS4 -> JavaScript

function calculateTotal(price, quantity) {
  return price * quantity;
}

const TAX_RATE = 0.1;

let subtotal = calculateTotal(25, 3);

let tax = subtotal * TAX_RATE;

let total = subtotal + tax;

function getDiscount(total) {
  if (total > 100) {
    return 20;
  }
  else   if (total > 50) {
    return 10;
  }
  else {
    return 0;
  }
}

function sumArray(numbers) {
  let sum = 0;
  for (let i = 0; i < 5; i++) {
    sum = sum + i;
  }
  return sum;
}

function factorial(n) {
  let result = 1;
  while (n > 1) {
    result = result * n;
    n = n - 1;
  }
  return result;
}

let numbers = [1, 2, 3, 4, 5];

function formatMessage(name, amount) {
  return "Hello " + name + ", your total is: " + amount;
}

trace("=== OpenFlex Neo Demo ===");

trace("Subtotal: " + subtotal);

trace("Tax: " + tax);

trace("Total: " + total);

trace("Discount: " + getDiscount(total));

trace("Sum: " + sumArray(numbers));

trace("5! = " + factorial(5));

trace(formatMessage("Alice", total));
