// Generated by OpenFlex Neo
// AS4 -> JavaScript

// OpenFlex Reactivity Runtime
const { Signal, Computed, createEffect } = require('./runtime/openflex-runtime.js');

const count = new Signal(0);

const message = new Signal("Hello, OpenFlex!");

createEffect(() => logCount());
function logCount() {
  trace("Count changed: " + count);
}

createEffect(() => logMessage());
function logMessage() {
  trace("Message: " + message);
}

function increment() {
  count = count + 1;
}

function decrement() {
  count = count - 1;
}

function setMessage(msg) {
  message = msg;
}

trace("=== OpenFlex Neo Reactivity Demo ===");

trace("");

trace("Initial state:");

trace("");

trace("Incrementing count...");

increment();

trace("");

trace("Incrementing again...");

increment();

trace("");

trace("Decrementing...");

decrement();

trace("");

trace("Changing message...");

setMessage("Reactivity is awesome!");

trace("");

trace("✨ Reactivity working perfectly! ✨");
);
