"""
Enhanced MXML Compiler - Generates Web Components
Full reactive bindings and event handling
"""

import re
from typing import List, Dict, Optional, Tuple
from compiler.parser.as4_parser import AS4Parser
from compiler.codegen.js_codegen import JSCodeGenerator


class MXMLElement:
    """Represents an MXML element"""
    def __init__(self, tag: str, attributes: Dict[str, str] = None, children: List['MXMLElement'] = None):
        self.tag = tag
        self.attributes = attributes or {}
        self.children = children or []


class EnhancedMXMLCompiler:
    """Compiles MXML to Web Components with reactive bindings"""

    def __init__(self):
        self.as4_parser = AS4Parser()
        self.js_codegen = JSCodeGenerator()
        self.component_counter = 0
        self.binding_map = {}  # Map element IDs to their bindings
        self.event_map = {}    # Map element IDs to their events

    def compile(self, mxml_source: str, filename: str = "<input>") -> str:
        """Compile MXML to JavaScript Web Components"""

        # Reset state for new compilation
        self.component_counter = 0
        self.binding_map = {}
        self.event_map = {}

        # Extract Script section
        script_content = self._extract_script(mxml_source)

        # Parse component tree
        root_element = self._parse_mxml_tree(mxml_source)

        # Generate JavaScript
        js_lines = []

        # Header
        js_lines.append("// Generated by OpenFlex Neo MXML Compiler")
        js_lines.append("// MXML -> Web Components with Reactivity")
        js_lines.append("")

        # Compile AS4 script if present
        has_reactivity = False
        if script_content:
            try:
                ast = self.as4_parser.parse(script_content, filename)
                script_js = self.js_codegen.generate(ast)

                # Check if reactivity is used
                if "Signal" in script_js:
                    has_reactivity = True

                # Add script code
                script_lines = script_js.split('\n')
                for line in script_lines:
                    if line and not line.startswith("//"):
                        js_lines.append(line)

            except Exception as e:
                js_lines.append(f"// Error parsing script: {e}")

        js_lines.append("")

        # Generate Web Component class
        js_lines.extend(self._generate_component_class(root_element, has_reactivity))

        # Define custom elements
        js_lines.append("")
        js_lines.append("// Register Custom Elements")
        js_lines.append("if (typeof window !== 'undefined') {")
        js_lines.append("  customElements.define('app-root', AppComponent);")
        js_lines.append("}")

        # Export for Node.js
        js_lines.append("")
        js_lines.append("// Export for Node.js/testing")
        js_lines.append("if (typeof module !== 'undefined' && module.exports) {")
        js_lines.append("  module.exports = { AppComponent };")
        js_lines.append("}")

        return "\n".join(js_lines)

    def _generate_component_class(self, root: MXMLElement, has_reactivity: bool) -> List[str]:
        """Generate Web Component class"""
        lines = []

        lines.append("// Application Component")
        lines.append("class AppComponent extends HTMLElement {")
        lines.append("  constructor() {")
        lines.append("    super();")
        lines.append("    this.attachShadow({ mode: 'open' });")
        lines.append("  }")
        lines.append("")
        lines.append("  connectedCallback() {")
        lines.append("    this.render();")

        # If reactive, set up effects
        if has_reactivity:
            lines.append("")
            lines.append("    // Set up reactive effects")
            lines.append("    this.setupReactivity();")

        lines.append("  }")
        lines.append("")
        lines.append("  render() {")
        lines.append("    this.shadowRoot.innerHTML = `")

        # Generate HTML
        html_lines = self._generate_html(root, indent=6)
        lines.extend(html_lines)

        lines.append("    `;")
        lines.append("")

        # Attach event handlers
        lines.append("    // Attach event handlers")
        event_handlers = self._extract_event_handlers(root)
        for handler in event_handlers:
            lines.append(f"    {handler}")

        lines.append("  }")

        # Generate setupReactivity if needed
        if has_reactivity:
            lines.append("")
            lines.append("  setupReactivity() {")
            lines.append("    // Auto-update DOM when reactive state changes")

            # Extract reactive bindings
            bindings = self._extract_bindings(root)
            for binding in bindings:
                lines.append(f"    {binding}")

            lines.append("  }")

        lines.append("}")

        return lines

    def _generate_html(self, element: MXMLElement, indent: int = 0) -> List[str]:
        """Generate HTML for element tree"""
        lines = []
        prefix = " " * indent

        if element.tag in ['Application', 'VBox', 'HBox']:
            # Container elements
            lines.append(f"{prefix}<div class='{element.tag.lower()}'>")

            for child in element.children:
                lines.extend(self._generate_html(child, indent + 2))

            lines.append(f"{prefix}</div>")

        elif element.tag == 'Label':
            text = element.attributes.get('text', '')
            # Check if text has binding
            if '{' in text:
                # Reactive binding - extract expression
                match = re.search(r'\{([^}]+)\}', text)
                if match:
                    expr = match.group(1).strip()
                    elem_id = f"binding_{self.component_counter}"
                    self.component_counter += 1

                    # Store binding for later
                    self.binding_map[elem_id] = {'text': text, 'expr': expr}

                    # Generate HTML with placeholder (will be updated by reactivity)
                    lines.append(f"{prefix}<span id='{elem_id}'></span>")
            else:
                lines.append(f"{prefix}<span>{text}</span>")

        elif element.tag == 'Button':
            label = element.attributes.get('label', 'Button')
            click = element.attributes.get('click', '')

            elem_id = f"btn_{self.component_counter}"
            self.component_counter += 1

            # Store event handler if present
            if click:
                self.event_map[elem_id] = click

            lines.append(f"{prefix}<button id='{elem_id}'>{label}</button>")

        return lines

    def _extract_bindings(self, element: MXMLElement) -> List[str]:
        """Extract reactive bindings and generate effect code"""
        bindings = []

        # Use the binding map we created during HTML generation
        for elem_id, binding_info in self.binding_map.items():
            text = binding_info['text']
            expr = binding_info['expr']

            # Build the text template (replace {expr} with interpolation)
            template = text.replace(f'{{{expr}}}', "' + " + f"{expr}.value + '")

            effect = f"createEffect(() => {{"
            effect += f"\n      const el = this.shadowRoot.getElementById('{elem_id}');"
            effect += f"\n      if (el) el.textContent = '{template}';"
            effect += "\n    });"
            bindings.append(effect)

        return bindings

    def _extract_event_handlers(self, element: MXMLElement) -> List[str]:
        """Extract event handlers"""
        handlers = []

        # Use the event map we created during HTML generation
        for elem_id, click_handler in self.event_map.items():
            # Handle different click formats
            if click_handler.startswith('{') and click_handler.endswith('}'):
                # Inline function {increment}
                func_name = click_handler[1:-1].strip()
                handler = f"this.shadowRoot.getElementById('{elem_id}').onclick = () => {func_name}();"
            else:
                # Direct function name
                handler = f"this.shadowRoot.getElementById('{elem_id}').onclick = () => {click_handler}();"

            handlers.append(handler)

        return handlers

    def _get_binding_id(self) -> str:
        """Generate unique binding ID"""
        self.component_counter += 1
        return f"binding_{self.component_counter}"

    def _parse_mxml_tree(self, mxml_source: str) -> MXMLElement:
        """Parse MXML into element tree (simplified parser)"""
        # Remove script section for parsing
        source = re.sub(r'<fx:Script[^>]*>.*?</fx:Script>', '', mxml_source, flags=re.DOTALL)

        # Find root element
        root_match = re.search(r'<([A-Z][a-zA-Z]+)[^>]*>', source)
        if not root_match:
            return MXMLElement('Application')

        root_tag = root_match.group(1)
        root = MXMLElement(root_tag)

        # Parse children (simplified - find VBox, Label, Button)
        vbox_match = re.search(r'<VBox[^>]*>(.*?)</VBox>', source, re.DOTALL)
        if vbox_match:
            vbox_content = vbox_match.group(1)
            vbox = MXMLElement('VBox')

            # Find Labels
            for label_match in re.finditer(r'<Label\s+text="([^"]+)"\s*/>', vbox_content):
                label = MXMLElement('Label', {'text': label_match.group(1)})
                vbox.children.append(label)

            # Find Buttons
            for button_match in re.finditer(r'<Button\s+label="([^"]+)"\s+click=\{([^}]+)\}\s*/>', vbox_content):
                button = MXMLElement('Button', {
                    'label': button_match.group(1),
                    'click': button_match.group(2)
                })
                vbox.children.append(button)

            root.children.append(vbox)

        return root

    def _extract_script(self, mxml_source: str) -> Optional[str]:
        """Extract AS4 code from fx:Script section"""
        script_match = re.search(
            r'<fx:Script[^>]*>(.*?)</fx:Script>',
            mxml_source,
            re.DOTALL
        )

        if script_match:
            script_content = script_match.group(1).strip()
            script_content = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', script_content, flags=re.DOTALL)
            return script_content

        return None
