"""
MXML Compiler - Compiles MXML to JavaScript
Integrates MXML parser with AS4 compiler
"""

import re
from pathlib import Path
from typing import Optional
from compiler.parser.as4_parser import AS4Parser
from compiler.codegen.js_codegen import JSCodeGenerator


class MXMLCompiler:
    """Compiles MXML files to JavaScript"""

    def __init__(self):
        self.as4_parser = AS4Parser()
        self.js_codegen = JSCodeGenerator()

    def compile(self, mxml_source: str, filename: str = "<input>") -> str:
        """Compile MXML to JavaScript"""

        # Extract Script section
        script_content = self._extract_script(mxml_source)

        # Extract component tree
        component_tree = self._extract_components(mxml_source)

        # Generate JavaScript
        js_lines = []

        # Add header
        js_lines.append("// Generated by OpenFlex Neo MXML Compiler")
        js_lines.append("// MXML -> JavaScript")
        js_lines.append("")

        # Compile AS4 script if present
        if script_content:
            try:
                ast = self.as4_parser.parse(script_content, filename)
                script_js = self.js_codegen.generate(ast)

                # Remove header from generated script (we have our own)
                script_lines = script_js.split('\n')[3:]  # Skip first 3 lines
                js_lines.extend(script_lines)
            except Exception as e:
                js_lines.append(f"// Error parsing script: {e}")

        js_lines.append("")

        # Generate component setup code
        js_lines.append("// Component Setup")
        js_lines.append("function setupComponent() {")

        # Extract component info
        root_component = self._get_root_component(mxml_source)
        js_lines.append(f"  // Root: {root_component}")

        # Generate component tree (simplified for now)
        if component_tree:
            for component in component_tree:
                js_lines.append(f"  // Component: {component}")

        js_lines.append("}")
        js_lines.append("")
        js_lines.append("// Initialize")
        js_lines.append("setupComponent();")

        return "\n".join(js_lines)

    def _extract_script(self, mxml_source: str) -> Optional[str]:
        """Extract AS4 code from fx:Script section"""
        # Find <fx:Script> ... </fx:Script>
        script_match = re.search(
            r'<fx:Script[^>]*>(.*?)</fx:Script>',
            mxml_source,
            re.DOTALL
        )

        if script_match:
            script_content = script_match.group(1).strip()
            # Remove CDATA if present
            script_content = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', script_content, flags=re.DOTALL)
            return script_content

        return None

    def _extract_components(self, mxml_source: str) -> list:
        """Extract component tree (simplified)"""
        components = []

        # Find all component tags (simplified - just tag names)
        tag_matches = re.findall(r'<([A-Z][a-zA-Z]+)', mxml_source)

        for tag in tag_matches:
            if not tag.startswith('fx:') and tag != 'Application':
                components.append(tag)

        return components

    def _get_root_component(self, mxml_source: str) -> str:
        """Get root component name"""
        match = re.search(r'<([A-Za-z]+)', mxml_source)
        if match:
            return match.group(1)
        return "Unknown"
