"""
Neo MXML Compiler - Versão Completa
Compila MXML (OpenFlex Neo) para Web Components com Reatividade Completa
Suporta TODOS os componentes Neo: VBox, HBox, Panel, Button, Label, TextInput, CheckBox, Repeater, etc.
"""

import re
import xml.etree.ElementTree as ET
from typing import List, Dict, Optional, Tuple, Set
from compiler.parser.as4_parser import AS4Parser
from compiler.parser.mxml_parser import preprocess_mxml_bindings
from compiler.codegen.js_codegen import JSCodeGenerator


class NeoMXMLCompiler:
    """Compilador MXML completo para componentes Neo"""

    # Namespaces MXML
    CORE_NS = "http://openflex.dev/core"
    NEO_NS = "http://openflex.dev/neo"

    # Componentes Neo suportados
    CONTAINER_COMPONENTS = {'Application', 'VBox', 'HBox', 'Panel', 'Box'}
    INPUT_COMPONENTS = {'TextInput', 'CheckBox', 'RadioButton', 'ComboBox'}
    DISPLAY_COMPONENTS = {'Label', 'Image', 'List'}
    BUTTON_COMPONENTS = {'Button'}
    REPEATER_COMPONENTS = {'Repeater'}
    DATA_COMPONENTS = {'DataGrid'}

    ALL_COMPONENTS = (CONTAINER_COMPONENTS | INPUT_COMPONENTS |
                     DISPLAY_COMPONENTS | BUTTON_COMPONENTS | REPEATER_COMPONENTS | DATA_COMPONENTS)

    # DnD-related attribute names
    DND_ATTRS = {
        'dragEnabled', 'dropEnabled', 'dragMoveEnabled',
        'dragStart', 'dragEnter', 'dragOver', 'dragExit', 'dragDrop', 'dragComplete'
    }

    # Selection-related attribute names
    SELECTION_ATTRS = {
        'selectedIndex', 'selectedItem', 'selectedIndices', 'allowMultipleSelection',
        'change', 'itemClick', 'itemDoubleClick'
    }

    def __init__(self):
        self.as4_parser = AS4Parser()
        self.js_codegen = JSCodeGenerator()
        self.component_counter = 0
        self.reactive_vars = set()
        self.styles = ""
        self.bindings = []  # Lista de bindings {id, attribute, expression}
        self.event_handlers = []  # Lista de event handlers {id, event, handler}
        self.uses_dnd = False
        self.dnd_configs = []  # Lista de dnd configs {id, component_type, ...}

    def _add_value_access(self, expr: str) -> str:
        """Add .value access to reactive variables in expression"""
        result = expr
        for var in self.reactive_vars:
            # Match the variable as a whole word, not already followed by .value
            pattern = r'\b' + re.escape(var) + r'(?!\.value)\b'
            replacement = var + '.value'
            result = re.sub(pattern, replacement, result)
        return result

    def compile(self, mxml_source: str, filename: str = "<input>") -> str:
        """Compila MXML para JavaScript"""

        # Reset state
        self.component_counter = 0
        self.reactive_vars = set()
        self.styles = ""
        self.bindings = []
        self.event_handlers = []
        self.uses_dnd = False
        self.dnd_configs = []

        # Preprocess MXML to normalize binding syntax before XML parsing
        mxml_source = preprocess_mxml_bindings(mxml_source)

        # Parse MXML como XML
        try:
            # Registrar namespaces
            ET.register_namespace('fx', self.CORE_NS)
            ET.register_namespace('', self.NEO_NS)

            # Parse XML
            root = ET.fromstring(mxml_source)
        except ET.ParseError as e:
            return f"// ERRO ao parsear MXML: {e}\n"

        # Extrair seções fx:Script e fx:Style
        script_content = self._extract_script(root)
        self.styles = self._extract_styles(root)

        # Gerar JavaScript
        lines = []

        # Header
        lines.append("// Generated by OpenFlex Neo MXML Compiler")
        lines.append("// Complete MXML -> Web Components with Full Reactivity")
        lines.append("")

        # Encapsular tudo em IIFE para evitar poluição do escopo global
        lines.append("(function() {")
        lines.append("")

        # Compilar script AS4
        has_reactivity = False
        script_lines = []
        if script_content:
            try:
                ast = self.as4_parser.parse(script_content, filename)
                script_js = self.js_codegen.generate(ast)

                # Detectar reatividade
                if "Signal" in script_js or "Computed" in script_js:
                    has_reactivity = True

                # Extrair variáveis reativas
                self.reactive_vars = self.js_codegen.reactive_vars.copy()

                # Indentar o script para dentro do IIFE
                for line in script_js.split('\n'):
                    script_lines.append(f"  {line}" if line.strip() else line)
            except Exception as e:
                script_lines.append(f"  // ERRO ao compilar script: {e}")

        lines.extend(script_lines)
        lines.append("")

        # Gerar Web Component (também indentado)
        # Note: this call populates self.uses_dnd via _extract_dnd_config
        component_lines = self._generate_web_component(root, has_reactivity)

        # Conditional DnD runtime import (after processing determines if DnD is used)
        if self.uses_dnd:
            lines.append("  // OpenFlex DnD Runtime")
            lines.append("  const { DragManager, DragSource, NeoFlexDragEvent, setupDragSource, setupDropTarget } =")
            lines.append("    (typeof window !== 'undefined' && window.OpenFlexDnD)")
            lines.append("    ? window.OpenFlexDnD")
            lines.append("    : require('./runtime/openflex-dnd.js');")
            lines.append("")

        for line in component_lines:
            lines.append(f"  {line}" if line.strip() else line)

        lines.append("")

        # Registrar custom element (dentro do IIFE)
        lines.append("  // Register Custom Element")
        lines.append("  if (typeof window !== 'undefined') {")
        lines.append("    customElements.define('app-root', AppComponent);")
        lines.append("  }")

        lines.append("")

        # Export para Node.js (dentro do IIFE)
        lines.append("  // Export for Node.js/testing")
        lines.append("  if (typeof module !== 'undefined' && module.exports) {")
        lines.append("    module.exports = { AppComponent };")
        lines.append("  }")

        lines.append("")

        # Fechar IIFE
        lines.append("})();")

        return "\n".join(lines)

    def _extract_script(self, root: ET.Element) -> Optional[str]:
        """Extrai conteúdo de fx:Script"""
        # Procurar fx:Script
        for child in root:
            if child.tag.endswith('Script'):
                script_text = child.text or ""
                # Remover CDATA se presente
                script_text = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', script_text, flags=re.DOTALL)
                return script_text.strip()
        return None

    def _extract_styles(self, root: ET.Element) -> str:
        """Extrai conteúdo de fx:Style"""
        for child in root:
            if child.tag.endswith('Style'):
                return (child.text or "").strip()
        return ""

    def _generate_web_component(self, root: ET.Element, has_reactivity: bool) -> List[str]:
        """Gera classe Web Component"""
        lines = []

        lines.append("// Application Component")
        lines.append("class AppComponent extends HTMLElement {")
        lines.append("  constructor() {")
        lines.append("    super();")
        lines.append("    this.attachShadow({ mode: 'open' });")
        lines.append("  }")
        lines.append("")
        lines.append("  connectedCallback() {")
        lines.append("    this.render();")

        if has_reactivity:
            lines.append("    this.setupReactivity();")

        lines.append("  }")
        lines.append("")
        lines.append("  render() {")

        # Gerar HTML
        html_lines = self._generate_html_from_element(root, indent=4)

        # Adicionar styles se houver
        style_tag = ""
        if self.styles:
            style_tag = f"<style>{self.styles}</style>"

        lines.append("    this.shadowRoot.innerHTML = `")
        if style_tag:
            lines.append(f"      {style_tag}")
        lines.extend(html_lines)
        lines.append("    `;")
        lines.append("")

        # Attachar event handlers
        lines.append("    // Attach event handlers")
        lines.append("    this.attachEventHandlers();")
        lines.append("  }")
        lines.append("")

        # Método para attachar events
        lines.append("  attachEventHandlers() {")
        for handler_info in self.event_handlers:
            elem_id = handler_info['id']
            event = handler_info['event']
            handler = handler_info['handler']
            lines.append(f"    const el_{elem_id} = this.shadowRoot.getElementById('{elem_id}');")

            # Determinar como gerar o handler
            if handler.strip().startswith('() =>') or handler.strip().startswith('function'):
                # Já é uma função, usar diretamente
                handler_code = handler
            elif '(' in handler:
                # É uma chamada de função, envolver em arrow function
                handler_code = f"() => {handler}"
            else:
                # É apenas um nome de função, envolver em arrow function e adicionar ()
                handler_code = f"() => {handler}()"

            lines.append(f"    if (el_{elem_id}) el_{elem_id}.addEventListener('{event}', {handler_code});")
        lines.append("  }")

        if has_reactivity:
            lines.append("")
            lines.append("  setupReactivity() {")
            for binding in self.bindings:
                elem_id = binding['id']
                attr = binding['attribute']
                expr = binding['expression']
                template = binding['template']
                is_style = binding.get('is_style', False)
                is_two_way = binding.get('is_two_way', False)
                is_repeater = binding.get('is_repeater', False)
                is_combobox = binding.get('is_combobox', False)
                is_list = binding.get('is_list', False)
                is_datagrid = binding.get('is_datagrid', False)

                # ComboBox especial
                if is_combobox:
                    template = binding.get('template', 'label')  # labelField
                    lines.append(f"    // ComboBox: {elem_id}")
                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const el = this.shadowRoot.getElementById('{elem_id}');")
                    lines.append(f"      if (!el) return;")
                    lines.append(f"      ")
                    lines.append(f"      // Limpar opções anteriores (exceto primeira)")
                    lines.append(f"      while (el.options.length > 1) el.remove(1);")
                    lines.append(f"      ")
                    lines.append(f"      // Renderizar opções do array")
                    expr_with_value = self._add_value_access(expr) if expr not in self.reactive_vars else f"{expr}.value"
                    items_var = 'comboItems' if expr.strip() == 'items' else 'items'
                    lines.append(f"      const {items_var} = {expr_with_value} || [];")
                    lines.append(f"      {items_var}.forEach((item, index) => {{")
                    lines.append(f"        const option = document.createElement('option');")
                    lines.append(f"        option.value = index;")
                    lines.append(f"        option.textContent = item.{template} || item || '';")
                    lines.append(f"        el.appendChild(option);")
                    lines.append(f"      }});")
                    lines.append(f"    }});")
                    continue

                # List especial
                if is_list:
                    template = binding.get('template', 'label')  # labelField
                    dnd_config = binding.get('dnd_config', None)
                    selection_config = binding.get('selection_config', None)
                    lines.append(f"    // List: {elem_id}")
                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const el = this.shadowRoot.getElementById('{elem_id}');")
                    lines.append(f"      if (!el) return;")
                    lines.append(f"      ")
                    lines.append(f"      // Limpar conteúdo anterior")
                    lines.append(f"      el.innerHTML = '';")
                    lines.append(f"      ")
                    # Selection: get current selectedIndex value
                    if selection_config and selection_config.get('selectedIndexVar'):
                        sel_var = selection_config['selectedIndexVar']
                        lines.append(f"      // Get current selection")
                        lines.append(f"      const currentSelectedIndex = {sel_var}.value;")
                        lines.append(f"      ")
                    lines.append(f"      // Renderizar itens do array")
                    expr_with_value = self._add_value_access(expr) if expr not in self.reactive_vars else f"{expr}.value"
                    items_var = 'listItems' if expr.strip() == 'items' else 'items'
                    lines.append(f"      const {items_var} = {expr_with_value} || [];")
                    lines.append(f"      {items_var}.forEach((item, index) => {{")
                    lines.append(f"        const itemEl = document.createElement('div');")
                    # Selection: add 'selected' class if this item is selected
                    if selection_config and selection_config.get('selectedIndexVar'):
                        lines.append(f"        itemEl.className = index === currentSelectedIndex ? 'neo-list-item selected' : 'neo-list-item';")
                    else:
                        lines.append(f"        itemEl.className = 'neo-list-item';")
                    lines.append(f"        itemEl.textContent = item.{template} || item || '';")
                    lines.append(f"        itemEl.dataset.index = index;")
                    # Selection: add click listener
                    if selection_config:
                        sel_var = selection_config.get('selectedIndexVar')
                        change_handler = selection_config.get('changeHandler', '')
                        item_click_handler = selection_config.get('itemClickHandler', '')
                        item_dblclick_handler = selection_config.get('itemDoubleClickHandler', '')
                        lines.append(f"        // Selection click handler")
                        lines.append(f"        itemEl.addEventListener('click', (e) => {{")
                        if sel_var:
                            lines.append(f"          const oldIndex = {sel_var}.value;")
                            lines.append(f"          {sel_var}.value = index;")
                        if item_click_handler:
                            lines.append(f"          {item_click_handler}({{ item: item, index: index, target: itemEl }});")
                        if change_handler and sel_var:
                            lines.append(f"          if (oldIndex !== index) {{")
                            lines.append(f"            {change_handler}({{ item: item, index: index, oldIndex: oldIndex }});")
                            lines.append(f"          }}")
                        elif change_handler:
                            lines.append(f"          {change_handler}({{ item: item, index: index }});")
                        lines.append(f"        }});")
                        if item_dblclick_handler:
                            lines.append(f"        itemEl.addEventListener('dblclick', (e) => {{")
                            lines.append(f"          {item_dblclick_handler}({{ item: item, index: index, target: itemEl }});")
                            lines.append(f"        }});")
                    # DnD: setupDragSource for each item
                    if dnd_config and dnd_config.get('dragEnabled'):
                        action = dnd_config.get('action', 'copy')
                        drag_start_handler = dnd_config.get('events', {}).get('dragStart', '')
                        drag_complete_handler = dnd_config.get('events', {}).get('dragComplete', '')
                        lines.append(f"        setupDragSource(itemEl, {{ item: item, index: index, action: '{action}'"
                                     + (f", onDragStart: (e) => {drag_start_handler}(e)" if drag_start_handler else "")
                                     + (f", onDragComplete: (e) => {drag_complete_handler}(e)" if drag_complete_handler else "")
                                     + f" }});")
                    lines.append(f"        el.appendChild(itemEl);")
                    lines.append(f"      }});")
                    # DnD: setupDropTarget on the container (after items are rendered)
                    if dnd_config and dnd_config.get('dropEnabled'):
                        drag_enter_handler = dnd_config.get('events', {}).get('dragEnter', '')
                        drag_over_handler = dnd_config.get('events', {}).get('dragOver', '')
                        drag_exit_handler = dnd_config.get('events', {}).get('dragExit', '')
                        drag_drop_handler = dnd_config.get('events', {}).get('dragDrop', '')
                        lines.append(f"      setupDropTarget(el, {{ childSelector: '.neo-list-item'"
                                     + (f", onDragEnter: (e) => {drag_enter_handler}(e)" if drag_enter_handler else "")
                                     + (f", onDragOver: (e) => {drag_over_handler}(e)" if drag_over_handler else "")
                                     + (f", onDragExit: (e) => {drag_exit_handler}(e)" if drag_exit_handler else "")
                                     + (f", onDragDrop: (e) => {drag_drop_handler}(e)" if drag_drop_handler else "")
                                     + f" }});")
                    lines.append(f"    }});")
                    continue

                # DataGrid especial
                if is_datagrid:
                    columns = binding.get('template', [])  # columns array
                    dnd_config = binding.get('dnd_config', None)
                    selection_config = binding.get('selection_config', None)
                    lines.append(f"    // DataGrid: {elem_id}")
                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const tbody = this.shadowRoot.getElementById('{elem_id}_body');")
                    lines.append(f"      if (!tbody) return;")
                    lines.append(f"      ")
                    lines.append(f"      // Limpar linhas anteriores")
                    lines.append(f"      tbody.innerHTML = '';")
                    lines.append(f"      ")
                    # Selection: get current selectedIndex value
                    if selection_config and selection_config.get('selectedIndexVar'):
                        sel_var = selection_config['selectedIndexVar']
                        lines.append(f"      // Get current selection")
                        lines.append(f"      const currentSelectedIndex = {sel_var}.value;")
                        lines.append(f"      ")
                    lines.append(f"      // Renderizar linhas do array")
                    expr_with_value = self._add_value_access(expr) if expr not in self.reactive_vars else f"{expr}.value"
                    items_var = 'gridData' if expr.strip() == 'items' else 'items'
                    lines.append(f"      const {items_var} = {expr_with_value} || [];")
                    lines.append(f"      {items_var}.forEach((item, index) => {{")
                    lines.append(f"        const row = document.createElement('tr');")
                    lines.append(f"        row.dataset.index = index;")
                    # Selection: add 'selected' class if this row is selected
                    if selection_config and selection_config.get('selectedIndexVar'):
                        lines.append(f"        row.className = index === currentSelectedIndex ? 'selected' : '';")
                    for col in columns:
                        data_field = col['dataField']
                        lines.append(f"        const td_{data_field} = document.createElement('td');")
                        lines.append(f"        td_{data_field}.textContent = item.{data_field} || '';")
                        lines.append(f"        row.appendChild(td_{data_field});")
                    # Selection: add click listener
                    if selection_config:
                        sel_var = selection_config.get('selectedIndexVar')
                        change_handler = selection_config.get('changeHandler', '')
                        item_click_handler = selection_config.get('itemClickHandler', '')
                        item_dblclick_handler = selection_config.get('itemDoubleClickHandler', '')
                        lines.append(f"        // Selection click handler")
                        lines.append(f"        row.addEventListener('click', (e) => {{")
                        if sel_var:
                            lines.append(f"          const oldIndex = {sel_var}.value;")
                            lines.append(f"          {sel_var}.value = index;")
                        if item_click_handler:
                            lines.append(f"          {item_click_handler}({{ item: item, index: index, target: row }});")
                        if change_handler and sel_var:
                            lines.append(f"          if (oldIndex !== index) {{")
                            lines.append(f"            {change_handler}({{ item: item, index: index, oldIndex: oldIndex }});")
                            lines.append(f"          }}")
                        elif change_handler:
                            lines.append(f"          {change_handler}({{ item: item, index: index }});")
                        lines.append(f"        }});")
                        if item_dblclick_handler:
                            lines.append(f"        row.addEventListener('dblclick', (e) => {{")
                            lines.append(f"          {item_dblclick_handler}({{ item: item, index: index, target: row }});")
                            lines.append(f"        }});")
                    # DnD: setupDragSource for each row
                    if dnd_config and dnd_config.get('dragEnabled'):
                        action = dnd_config.get('action', 'copy')
                        drag_start_handler = dnd_config.get('events', {}).get('dragStart', '')
                        drag_complete_handler = dnd_config.get('events', {}).get('dragComplete', '')
                        lines.append(f"        row.className = (row.className ? row.className + ' ' : '') + 'neo-datagrid-row';")
                        lines.append(f"        setupDragSource(row, {{ item: item, index: index, action: '{action}'"
                                     + (f", onDragStart: (e) => {drag_start_handler}(e)" if drag_start_handler else "")
                                     + (f", onDragComplete: (e) => {drag_complete_handler}(e)" if drag_complete_handler else "")
                                     + f" }});")
                    lines.append(f"        tbody.appendChild(row);")
                    lines.append(f"      }});")
                    # DnD: setupDropTarget on tbody (after rows are rendered)
                    if dnd_config and dnd_config.get('dropEnabled'):
                        drag_enter_handler = dnd_config.get('events', {}).get('dragEnter', '')
                        drag_over_handler = dnd_config.get('events', {}).get('dragOver', '')
                        drag_exit_handler = dnd_config.get('events', {}).get('dragExit', '')
                        drag_drop_handler = dnd_config.get('events', {}).get('dragDrop', '')
                        lines.append(f"      const dgContainer = this.shadowRoot.getElementById('{elem_id}');")
                        lines.append(f"      setupDropTarget(dgContainer, {{ childSelector: 'tr.neo-datagrid-row'"
                                     + (f", onDragEnter: (e) => {drag_enter_handler}(e)" if drag_enter_handler else "")
                                     + (f", onDragOver: (e) => {drag_over_handler}(e)" if drag_over_handler else "")
                                     + (f", onDragExit: (e) => {drag_exit_handler}(e)" if drag_exit_handler else "")
                                     + (f", onDragDrop: (e) => {drag_drop_handler}(e)" if drag_drop_handler else "")
                                     + f" }});")
                    lines.append(f"    }});")
                    continue

                # Repeater especial
                if is_repeater:
                    lines.append(f"    // Repeater: {elem_id}")
                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const el = this.shadowRoot.getElementById('{elem_id}');")
                    lines.append(f"      if (!el) return;")
                    lines.append(f"      ")
                    lines.append(f"      // Limpar conteúdo anterior")
                    lines.append(f"      el.innerHTML = '';")
                    lines.append(f"      ")
                    lines.append(f"      // Renderizar itens do array")
                    # Use _add_value_access to correctly handle complex expressions like history.slice()
                    # Use itemsArray to avoid shadowing if expr is 'items'
                    expr_with_value = self._add_value_access(expr) if expr not in self.reactive_vars else f"{expr}.value"
                    items_var = 'itemsArray' if expr.strip() == 'items' else 'items'
                    lines.append(f"      const {items_var} = {expr_with_value} || [];")
                    lines.append(f"      {items_var}.forEach((item, index) => {{")
                    lines.append(f"        const itemEl = document.createElement('div');")
                    lines.append(f"        itemEl.className = 'repeater-item';")
                    lines.append(f"        itemEl.textContent = item.text || JSON.stringify(item);")
                    lines.append(f"        el.appendChild(itemEl);")
                    lines.append(f"      }});")
                    lines.append(f"    }});")
                    continue

                # Detectar se a expressão contém variáveis reativas
                # Verifica se expr é uma variável simples OU se contém variáveis reativas
                uses_reactive_var = expr in self.reactive_vars or any(var in expr for var in self.reactive_vars)

                if uses_reactive_var:
                    # Mapear atributos MXML para propriedades DOM
                    dom_attr = attr
                    if attr == 'styleClass':
                        dom_attr = 'className'

                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const el = this.shadowRoot.getElementById('{elem_id}');")

                    # Se template tem binding simples {expr}, usar direto
                    if template == f'{{{expr}}}':
                        # Atributos de cor devem usar style.color sem unidade
                        if attr in ['color', 'backgroundColor', 'borderColor']:
                            if expr in self.reactive_vars:
                                lines.append(f"      if (el) el.style.{attr} = {expr}.value;")
                            else:
                                expr_with_value = self._add_value_access(expr)
                                lines.append(f"      if (el) el.style.{attr} = {expr_with_value};")
                        elif is_style:
                            # Atributos de estilo com px (width, height, etc)
                            # Check if expression already contains a unit (%, px, em, rem, vh, vw)
                            has_unit = any(unit in expr for unit in ["'%'", '"%"', "'px'", '"px"', "'em'", '"em"', "'rem'", '"rem"', "'vh'", '"vh"', "'vw'", '"vw"'])

                            if expr in self.reactive_vars:
                                if has_unit:
                                    lines.append(f"      if (el) el.style.{attr} = {expr}.value;")
                                else:
                                    lines.append(f"      if (el) el.style.{attr} = {expr}.value + 'px';")
                            else:
                                # Expressão que referencia variáveis reativas
                                expr_with_value = self._add_value_access(expr)
                                if has_unit:
                                    lines.append(f"      if (el) el.style.{attr} = {expr_with_value};")
                                else:
                                    lines.append(f"      if (el) el.style.{attr} = ({expr_with_value}) + 'px';")
                        elif attr == 'visible':
                            # Visibilidade
                            if expr in self.reactive_vars:
                                lines.append(f"      if (el) el.style.display = {expr}.value ? 'block' : 'none';")
                            else:
                                expr_with_value = self._add_value_access(expr)
                                lines.append(f"      if (el) el.style.display = ({expr_with_value}) ? 'block' : 'none';")
                        else:
                            # Atributo normal (textContent, value, className, etc)
                            if expr in self.reactive_vars:
                                lines.append(f"      if (el) el.{dom_attr} = {expr}.value;")
                            else:
                                # Expressão complexa - avaliar diretamente com .value
                                expr_with_value = self._add_value_access(expr)
                                lines.append(f"      if (el) el.{dom_attr} = {expr_with_value};")
                    else:
                        # Template complexo: "Count: {count}" ou "A) + currentQ.answers[0]"
                        # Substituir binding mantendo a expressão
                        if expr in self.reactive_vars:
                            template_js = template.replace(f'{{{expr}}}', f"${{{expr}.value}}")
                        else:
                            # Expressão complexa - avaliar diretamente com .value
                            expr_with_value = self._add_value_access(expr)
                            template_js = template.replace(f'{{{expr}}}', f"${{{expr_with_value}}}")
                        lines.append(f"      if (el) el.{dom_attr} = `{template_js}`;")

                    lines.append(f"    }});")

                    # Two-way binding adicional
                    if is_two_way:
                        lines.append(f"    ")
                        lines.append(f"    // Two-way binding para {elem_id}")
                        lines.append(f"    const el_{elem_id} = this.shadowRoot.getElementById('{elem_id}');")
                        lines.append(f"    if (el_{elem_id}) {{")
                        lines.append(f"      el_{elem_id}.addEventListener('input', (e) => {{")
                        lines.append(f"        {expr}.value = e.target.value;")
                        lines.append(f"      }});")
                        lines.append(f"    }}")

            lines.append("  }")

        lines.append("}")

        return lines

    def _process_attributes(self, element: ET.Element, elem_id: str) -> Dict[str, str]:
        """Processa atributos do elemento, detectando bindings"""
        static_attrs = {}

        for attr_name, attr_value in element.attrib.items():
            # Ignorar atributos especiais já processados
            if attr_name in ['text', 'label', 'click', 'placeholder', 'title', 'dataProvider']:
                continue

            # Ignorar DnD attributes (handled separately)
            if attr_name in self.DND_ATTRS:
                continue

            # Ignorar Selection attributes (handled separately)
            if attr_name in self.SELECTION_ATTRS:
                continue

            # Detectar binding
            if '{' in attr_value and '}' in attr_value:
                match = re.search(r'\{([^}]+)\}', attr_value)
                if match:
                    expr = match.group(1).strip()
                    # Se é apenas {expr}, binding direto
                    if attr_value == f'{{{expr}}}':
                        self.bindings.append({
                            'id': elem_id,
                            'attribute': attr_name,
                            'expression': expr,
                            'template': attr_value,
                            'is_style': attr_name in ['width', 'height', 'gap', 'padding']
                        })
                    else:
                        # Template string
                        self.bindings.append({
                            'id': elem_id,
                            'attribute': attr_name,
                            'expression': expr,
                            'template': attr_value,
                            'is_style': False
                        })
            else:
                # Atributo estático
                static_attrs[attr_name] = attr_value

        return static_attrs

    def _build_style_string(self, attrs: Dict[str, str]) -> str:
        """Constrói string de estilo inline a partir dos atributos"""
        styles = []

        def add_size_attr(name: str, value: str):
            """Adiciona atributo de tamanho (px apenas se não tiver % ou outra unidade)"""
            if '%' in value or 'px' in value or 'em' in value or 'rem' in value:
                styles.append(f"{name}: {value}")
            else:
                styles.append(f"{name}: {value}px")

        # Dimensões
        if 'width' in attrs:
            add_size_attr('width', attrs['width'])
        if 'height' in attrs:
            add_size_attr('height', attrs['height'])

        # Espaçamento
        if 'gap' in attrs:
            add_size_attr('gap', attrs['gap'])
        if 'padding' in attrs:
            add_size_attr('padding', attrs['padding'])

        # Fonte
        if 'fontSize' in attrs:
            add_size_attr('font-size', attrs['fontSize'])
        if 'color' in attrs:
            styles.append(f"color: {attrs['color']}")

        # Adicionar style inline do MXML (para casos como style="max-width: 1600px")
        if 'style' in attrs:
            styles.append(attrs['style'])

        if styles:
            return f" style='{'; '.join(styles)}'"
        return ""

    def _build_class_string(self, base_class: str, attrs: Dict[str, str]) -> str:
        """Constrói string de classes CSS combinando base + styleClass + alinhamento"""
        classes = [base_class]

        # Adicionar styleClass se existir (sem duplicar base_class)
        if 'styleClass' in attrs:
            for cls in attrs['styleClass'].split():
                if cls not in classes:
                    classes.append(cls)

        # Adicionar classes de alinhamento
        if 'horizontalAlign' in attrs:
            classes.append(f"h-align-{attrs['horizontalAlign']}")
        if 'verticalAlign' in attrs:
            classes.append(f"v-align-{attrs['verticalAlign']}")

        return f" class='{' '.join(classes)}'"

    def _get_alignment_classes(self, attrs: Dict[str, str]) -> str:
        """Retorna classes CSS para alinhamento"""
        classes = []

        if 'horizontalAlign' in attrs:
            classes.append(f"h-align-{attrs['horizontalAlign']}")
        if 'verticalAlign' in attrs:
            classes.append(f"v-align-{attrs['verticalAlign']}")

        if classes:
            return " " + " ".join(classes)
        return ""

    def _extract_dnd_config(self, element: ET.Element, elem_id: str, component_type: str) -> Optional[Dict]:
        """Extract drag-and-drop configuration from element attributes"""
        drag_enabled = element.get('dragEnabled', 'false').lower() == 'true'
        drop_enabled = element.get('dropEnabled', 'false').lower() == 'true'
        drag_move_enabled = element.get('dragMoveEnabled', 'false').lower() == 'true'

        if not drag_enabled and not drop_enabled:
            return None

        self.uses_dnd = True

        # Extract DnD event handlers
        dnd_events = {}
        for evt_name in ['dragStart', 'dragEnter', 'dragOver', 'dragExit', 'dragDrop', 'dragComplete']:
            handler = element.get(evt_name, '')
            if handler:
                # Remove {} if present
                handler = handler.strip('{}').strip()
                dnd_events[evt_name] = handler

        config = {
            'id': elem_id,
            'component_type': component_type,
            'dragEnabled': drag_enabled,
            'dropEnabled': drop_enabled,
            'action': 'move' if drag_move_enabled else 'copy',
            'events': dnd_events
        }

        self.dnd_configs.append(config)
        return config

    def _extract_selection_config(self, element: ET.Element, elem_id: str, component_type: str) -> Optional[Dict]:
        """Extract selection configuration from element attributes"""
        selected_index = element.get('selectedIndex', '')
        selected_item = element.get('selectedItem', '')
        allow_multiple = element.get('allowMultipleSelection', 'false').lower() == 'true'

        # Extract selection event handlers
        change_handler = element.get('change', '')
        item_click_handler = element.get('itemClick', '')
        item_double_click_handler = element.get('itemDoubleClick', '')

        # Check if any selection feature is used
        has_selection = bool(selected_index or selected_item or change_handler or
                           item_click_handler or item_double_click_handler)

        if not has_selection:
            return None

        # Parse selectedIndex binding
        selected_index_var = None
        if selected_index and '{' in selected_index and '}' in selected_index:
            match = re.search(r'\{([^}]+)\}', selected_index)
            if match:
                selected_index_var = match.group(1).strip()

        # Clean handlers (remove {} if present)
        if change_handler:
            change_handler = change_handler.strip('{}').strip()
        if item_click_handler:
            item_click_handler = item_click_handler.strip('{}').strip()
        if item_double_click_handler:
            item_double_click_handler = item_double_click_handler.strip('{}').strip()

        return {
            'id': elem_id,
            'component_type': component_type,
            'selectedIndexVar': selected_index_var,
            'allowMultipleSelection': allow_multiple,
            'changeHandler': change_handler,
            'itemClickHandler': item_click_handler,
            'itemDoubleClickHandler': item_double_click_handler
        }

    def _generate_html_from_element(self, element: ET.Element, indent: int = 0) -> List[str]:
        """Gera HTML recursivamente a partir do elemento XML"""
        lines = []
        prefix = " " * indent

        # Remover namespace do tag
        tag = element.tag.split('}')[-1] if '}' in element.tag else element.tag

        # Ignorar fx: elements
        if element.tag.startswith('{' + self.CORE_NS):
            return lines

        # Processar baseado no tipo de componente
        if tag == 'Application':
            elem_id = f"app_{self.component_counter}"
            self.component_counter += 1

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-application', static_attrs)
            style_str = self._build_style_string(static_attrs)

            lines.append(f"{prefix}<div id='{elem_id}'{class_str}{style_str}>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag in ['VBox', 'HBox']:
            elem_id = f"{'vbox' if tag == 'VBox' else 'hbox'}_{self.component_counter}"
            self.component_counter += 1

            css_class = 'neo-vbox' if tag == 'VBox' else 'neo-hbox'

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string(css_class, static_attrs)
            style_str = self._build_style_string(static_attrs)

            lines.append(f"{prefix}<div id='{elem_id}'{class_str}{style_str}>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag == 'Panel':
            elem_id = f"panel_{self.component_counter}"
            self.component_counter += 1

            title = element.get('title', '')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-panel', static_attrs)
            style_str = self._build_style_string(static_attrs)

            lines.append(f"{prefix}<div id='{elem_id}'{class_str}{style_str}>")
            if title:
                lines.append(f"{prefix}  <div class='neo-panel-header'>{title}</div>")
            lines.append(f"{prefix}  <div class='neo-panel-body'>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 4))
            lines.append(f"{prefix}  </div>")
            lines.append(f"{prefix}</div>")

        elif tag == 'Label':
            text = element.get('text', '')
            elem_id = f"label_{self.component_counter}"
            self.component_counter += 1

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-label', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Detectar data binding
            if '{' in text and '}' in text:
                # Extrair expressão
                match = re.search(r'\{([^}]+)\}', text)
                if match:
                    expr = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'textContent',
                        'expression': expr,
                        'template': text
                    })
                    # Placeholder no HTML (será atualizado por reatividade)
                    lines.append(f"{prefix}<span id='{elem_id}'{class_str}{style_str}></span>")
            else:
                lines.append(f"{prefix}<span id='{elem_id}'{class_str}{style_str}>{text}</span>")

        elif tag == 'Button':
            label = element.get('label', 'Button')
            click = element.get('click', '')
            elem_id = f"btn_{self.component_counter}"
            self.component_counter += 1

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-button', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Detectar event handler
            if click:
                # Remover {} se presente
                handler = click.strip('{}').strip()
                self.event_handlers.append({
                    'id': elem_id,
                    'event': 'click',
                    'handler': handler
                })

            # Detectar data binding no label
            label_content = label
            if '{' in label and '}' in label:
                # Extrair expressão
                match = re.search(r'\{([^}]+)\}', label)
                if match:
                    expr = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'textContent',
                        'expression': expr,
                        'template': label
                    })
                    # Placeholder no HTML (será atualizado por reatividade)
                    label_content = ''

            lines.append(f"{prefix}<button id='{elem_id}'{class_str}{style_str}>{label_content}</button>")

        elif tag == 'TextInput':
            elem_id = f"input_{self.component_counter}"
            self.component_counter += 1
            placeholder = element.get('placeholder', '')
            text_binding = element.get('text', '')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-textinput', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Two-way binding para text
            if text_binding and '{' in text_binding and '}' in text_binding:
                match = re.search(r'\{([^}]+)\}', text_binding)
                if match:
                    var_name = match.group(1).strip()
                    # Adicionar binding bidirecional
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'value',
                        'expression': var_name,
                        'template': text_binding,
                        'is_two_way': True
                    })

            lines.append(f"{prefix}<input type='text' id='{elem_id}'{class_str} placeholder='{placeholder}'{style_str} />")

        elif tag == 'CheckBox':
            elem_id = f"checkbox_{self.component_counter}"
            self.component_counter += 1

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-checkbox', static_attrs)
            style_str = self._build_style_string(static_attrs)

            lines.append(f"{prefix}<input type='checkbox' id='{elem_id}'{class_str}{style_str} />")

        elif tag == 'ComboBox':
            elem_id = f"combobox_{self.component_counter}"
            self.component_counter += 1

            data_provider = element.get('dataProvider', '')
            label_field = element.get('labelField', 'label')
            selected_index = element.get('selectedIndex', '0')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-combobox', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Detectar binding no dataProvider
            if data_provider and '{' in data_provider and '}' in data_provider:
                match = re.search(r'\{([^}]+)\}', data_provider)
                if match:
                    array_var = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'combobox',
                        'expression': array_var,
                        'template': label_field,
                        'is_combobox': True
                    })

            lines.append(f"{prefix}<select id='{elem_id}'{class_str}{style_str}>")
            lines.append(f"{prefix}  <option>-- Select --</option>")
            lines.append(f"{prefix}</select>")

        elif tag == 'List':
            elem_id = f"list_{self.component_counter}"
            self.component_counter += 1

            data_provider = element.get('dataProvider', '')
            label_field = element.get('labelField', 'label')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-list', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Extract DnD config
            dnd_config = self._extract_dnd_config(element, elem_id, 'List')

            # Extract Selection config
            selection_config = self._extract_selection_config(element, elem_id, 'List')

            # Detectar binding no dataProvider
            if data_provider and '{' in data_provider and '}' in data_provider:
                match = re.search(r'\{([^}]+)\}', data_provider)
                if match:
                    array_var = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'list',
                        'expression': array_var,
                        'template': label_field,
                        'is_list': True,
                        'dnd_config': dnd_config,
                        'selection_config': selection_config
                    })

            lines.append(f"{prefix}<div id='{elem_id}'{class_str}{style_str}>")
            lines.append(f"{prefix}  <!-- List items will be dynamically generated -->")
            lines.append(f"{prefix}</div>")

        elif tag == 'DataGrid':
            elem_id = f"datagrid_{self.component_counter}"
            self.component_counter += 1

            data_provider = element.get('dataProvider', '')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            class_str = self._build_class_string('neo-datagrid', static_attrs)
            style_str = self._build_style_string(static_attrs)

            # Extract DnD config
            dnd_config = self._extract_dnd_config(element, elem_id, 'DataGrid')

            # Extract Selection config
            selection_config = self._extract_selection_config(element, elem_id, 'DataGrid')

            # Coletar colunas
            columns = []
            for child in element:
                if child.tag.endswith('DataGridColumn') or child.tag == 'DataGridColumn':
                    col_info = {
                        'headerText': child.get('headerText', 'Column'),
                        'dataField': child.get('dataField', 'field'),
                        'width': child.get('width', '100')
                    }
                    columns.append(col_info)

            # Detectar binding no dataProvider
            if data_provider and '{' in data_provider and '}' in data_provider:
                match = re.search(r'\{([^}]+)\}', data_provider)
                if match:
                    array_var = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'datagrid',
                        'expression': array_var,
                        'template': columns,
                        'is_datagrid': True,
                        'dnd_config': dnd_config,
                        'selection_config': selection_config
                    })

            lines.append(f"{prefix}<div id='{elem_id}'{class_str}{style_str}>")
            lines.append(f"{prefix}  <table class='neo-datagrid-table'>")
            lines.append(f"{prefix}    <thead>")
            lines.append(f"{prefix}      <tr>")
            for col in columns:
                lines.append(f"{prefix}        <th style='width: {col['width']}px'>{col['headerText']}</th>")
            lines.append(f"{prefix}      </tr>")
            lines.append(f"{prefix}    </thead>")
            lines.append(f"{prefix}    <tbody id='{elem_id}_body'>")
            lines.append(f"{prefix}      <!-- Rows will be dynamically generated -->")
            lines.append(f"{prefix}    </tbody>")
            lines.append(f"{prefix}  </table>")
            lines.append(f"{prefix}</div>")

        elif tag == 'Box':
            elem_id = f"box_{self.component_counter}"
            self.component_counter += 1

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)
            style_str = self._build_style_string(static_attrs)

            lines.append(f"{prefix}<div id='{elem_id}' class='neo-box'{style_str}>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag == 'Repeater':
            # Repeater com dataProvider
            elem_id = f"repeater_{self.component_counter}"
            self.component_counter += 1

            data_provider = element.get('dataProvider', '')

            # Processar atributos
            static_attrs = self._process_attributes(element, elem_id)

            # Detectar binding no dataProvider
            if data_provider and '{' in data_provider and '}' in data_provider:
                match = re.search(r'\{([^}]+)\}', data_provider)
                if match:
                    array_var = match.group(1).strip()

                    # Guardar informação do Repeater para gerar código dinâmico
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'repeater',
                        'expression': array_var,
                        'template': '',
                        'is_repeater': True,
                        'child_template': element  # Guardar template dos filhos
                    })

            lines.append(f"{prefix}<div id='{elem_id}' class='neo-repeater'>")
            lines.append(f"{prefix}  <!-- Repeater content will be dynamically generated -->")
            lines.append(f"{prefix}</div>")

        return lines

