"""
Neo MXML Compiler - Versão Completa
Compila MXML (OpenFlex Neo) para Web Components com Reatividade Completa
Suporta TODOS os componentes Neo: VBox, HBox, Panel, Button, Label, TextInput, CheckBox, Repeater, etc.
"""

import re
import xml.etree.ElementTree as ET
from typing import List, Dict, Optional, Tuple, Set
from compiler.parser.as4_parser import AS4Parser
from compiler.codegen.js_codegen import JSCodeGenerator


class NeoMXMLCompiler:
    """Compilador MXML completo para componentes Neo"""

    # Namespaces MXML
    CORE_NS = "http://openflex.dev/core"
    NEO_NS = "http://openflex.dev/neo"

    # Componentes Neo suportados
    CONTAINER_COMPONENTS = {'Application', 'VBox', 'HBox', 'Panel', 'Box'}
    INPUT_COMPONENTS = {'TextInput', 'CheckBox', 'RadioButton'}
    DISPLAY_COMPONENTS = {'Label', 'Image'}
    BUTTON_COMPONENTS = {'Button'}
    REPEATER_COMPONENTS = {'Repeater'}

    ALL_COMPONENTS = (CONTAINER_COMPONENTS | INPUT_COMPONENTS |
                     DISPLAY_COMPONENTS | BUTTON_COMPONENTS | REPEATER_COMPONENTS)

    def __init__(self):
        self.as4_parser = AS4Parser()
        self.js_codegen = JSCodeGenerator()
        self.component_counter = 0
        self.reactive_vars = set()
        self.styles = ""
        self.bindings = []  # Lista de bindings {id, attribute, expression}
        self.event_handlers = []  # Lista de event handlers {id, event, handler}

    def compile(self, mxml_source: str, filename: str = "<input>") -> str:
        """Compila MXML para JavaScript"""

        # Reset state
        self.component_counter = 0
        self.reactive_vars = set()
        self.styles = ""
        self.bindings = []
        self.event_handlers = []

        # Parse MXML como XML
        try:
            # Registrar namespaces
            ET.register_namespace('fx', self.CORE_NS)
            ET.register_namespace('', self.NEO_NS)

            # Parse XML
            root = ET.fromstring(mxml_source)
        except ET.ParseError as e:
            return f"// ERRO ao parsear MXML: {e}\n"

        # Extrair seções fx:Script e fx:Style
        script_content = self._extract_script(root)
        self.styles = self._extract_styles(root)

        # Gerar JavaScript
        lines = []

        # Header
        lines.append("// Generated by OpenFlex Neo MXML Compiler")
        lines.append("// Complete MXML -> Web Components with Full Reactivity")
        lines.append("")

        # Compilar script AS4
        has_reactivity = False
        if script_content:
            try:
                ast = self.as4_parser.parse(script_content, filename)
                script_js = self.js_codegen.generate(ast)

                # Detectar reatividade
                if "Signal" in script_js or "Computed" in script_js:
                    has_reactivity = True

                # Extrair variáveis reativas
                self.reactive_vars = self.js_codegen.reactive_vars.copy()

                lines.append(script_js)
            except Exception as e:
                lines.append(f"// ERRO ao compilar script: {e}")

        lines.append("")

        # Gerar Web Component
        component_lines = self._generate_web_component(root, has_reactivity)
        lines.extend(component_lines)

        # Registrar custom element
        lines.append("")
        lines.append("// Register Custom Element")
        lines.append("if (typeof window !== 'undefined') {")
        lines.append("  customElements.define('app-root', AppComponent);")
        lines.append("}")

        # Export para Node.js
        lines.append("")
        lines.append("// Export for Node.js/testing")
        lines.append("if (typeof module !== 'undefined' && module.exports) {")
        lines.append("  module.exports = { AppComponent };")
        lines.append("}")

        return "\n".join(lines)

    def _extract_script(self, root: ET.Element) -> Optional[str]:
        """Extrai conteúdo de fx:Script"""
        # Procurar fx:Script
        for child in root:
            if child.tag.endswith('Script'):
                script_text = child.text or ""
                # Remover CDATA se presente
                script_text = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', script_text, flags=re.DOTALL)
                return script_text.strip()
        return None

    def _extract_styles(self, root: ET.Element) -> str:
        """Extrai conteúdo de fx:Style"""
        for child in root:
            if child.tag.endswith('Style'):
                return (child.text or "").strip()
        return ""

    def _generate_web_component(self, root: ET.Element, has_reactivity: bool) -> List[str]:
        """Gera classe Web Component"""
        lines = []

        lines.append("// Application Component")
        lines.append("class AppComponent extends HTMLElement {")
        lines.append("  constructor() {")
        lines.append("    super();")
        lines.append("    this.attachShadow({ mode: 'open' });")
        lines.append("  }")
        lines.append("")
        lines.append("  connectedCallback() {")
        lines.append("    this.render();")

        if has_reactivity:
            lines.append("    this.setupReactivity();")

        lines.append("  }")
        lines.append("")
        lines.append("  render() {")

        # Gerar HTML
        html_lines = self._generate_html_from_element(root, indent=4)

        # Adicionar styles se houver
        style_tag = ""
        if self.styles:
            style_tag = f"<style>{self.styles}</style>"

        lines.append("    this.shadowRoot.innerHTML = `")
        if style_tag:
            lines.append(f"      {style_tag}")
        lines.extend(html_lines)
        lines.append("    `;")
        lines.append("")

        # Attachar event handlers
        lines.append("    // Attach event handlers")
        lines.append("    this.attachEventHandlers();")
        lines.append("  }")
        lines.append("")

        # Método para attachar events
        lines.append("  attachEventHandlers() {")
        for handler_info in self.event_handlers:
            elem_id = handler_info['id']
            event = handler_info['event']
            handler = handler_info['handler']
            lines.append(f"    const el_{elem_id} = this.shadowRoot.getElementById('{elem_id}');")
            lines.append(f"    if (el_{elem_id}) el_{elem_id}.addEventListener('{event}', () => {handler}());")
        lines.append("  }")

        if has_reactivity:
            lines.append("")
            lines.append("  setupReactivity() {")
            for binding in self.bindings:
                elem_id = binding['id']
                attr = binding['attribute']
                expr = binding['expression']
                template = binding['template']

                # Detectar se a expressão é uma variável reativa
                if expr in self.reactive_vars:
                    lines.append(f"    createEffect(() => {{")
                    lines.append(f"      const el = this.shadowRoot.getElementById('{elem_id}');")

                    # Se template tem binding simples {expr}, usar direto
                    if template == f'{{{expr}}}':
                        lines.append(f"      if (el) el.{attr} = {expr}.value;")
                    else:
                        # Template complexo: "Count: {count}"
                        template_js = template.replace(f'{{{expr}}}', f"${{{expr}.value}}")
                        lines.append(f"      if (el) el.{attr} = `{template_js}`;")

                    lines.append(f"    }});")
            lines.append("  }")

        lines.append("}")

        return lines

    def _generate_html_from_element(self, element: ET.Element, indent: int = 0) -> List[str]:
        """Gera HTML recursivamente a partir do elemento XML"""
        lines = []
        prefix = " " * indent

        # Remover namespace do tag
        tag = element.tag.split('}')[-1] if '}' in element.tag else element.tag

        # Ignorar fx: elements
        if element.tag.startswith('{' + self.CORE_NS):
            return lines

        # Processar baseado no tipo de componente
        if tag == 'Application':
            lines.append(f"{prefix}<div class='neo-application'>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag in ['VBox', 'HBox']:
            css_class = 'neo-vbox' if tag == 'VBox' else 'neo-hbox'
            lines.append(f"{prefix}<div class='{css_class}'>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag == 'Panel':
            title = element.get('title', '')
            lines.append(f"{prefix}<div class='neo-panel'>")
            if title:
                lines.append(f"{prefix}  <div class='neo-panel-header'>{title}</div>")
            lines.append(f"{prefix}  <div class='neo-panel-body'>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 4))
            lines.append(f"{prefix}  </div>")
            lines.append(f"{prefix}</div>")

        elif tag == 'Label':
            text = element.get('text', '')
            elem_id = f"label_{self.component_counter}"
            self.component_counter += 1

            # Detectar data binding
            if '{' in text and '}' in text:
                # Extrair expressão
                match = re.search(r'\{([^}]+)\}', text)
                if match:
                    expr = match.group(1).strip()
                    self.bindings.append({
                        'id': elem_id,
                        'attribute': 'textContent',
                        'expression': expr,
                        'template': text
                    })
                    # Placeholder no HTML (será atualizado por reatividade)
                    lines.append(f"{prefix}<span id='{elem_id}' class='neo-label'></span>")
            else:
                lines.append(f"{prefix}<span id='{elem_id}' class='neo-label'>{text}</span>")

        elif tag == 'Button':
            label = element.get('label', 'Button')
            click = element.get('click', '')
            elem_id = f"btn_{self.component_counter}"
            self.component_counter += 1

            # Detectar event handler
            if click:
                # Remover {} se presente
                handler = click.strip('{}').strip()
                self.event_handlers.append({
                    'id': elem_id,
                    'event': 'click',
                    'handler': handler
                })

            lines.append(f"{prefix}<button id='{elem_id}' class='neo-button'>{label}</button>")

        elif tag == 'TextInput':
            elem_id = f"input_{self.component_counter}"
            self.component_counter += 1
            placeholder = element.get('placeholder', '')
            lines.append(f"{prefix}<input type='text' id='{elem_id}' class='neo-textinput' placeholder='{placeholder}' />")

        elif tag == 'CheckBox':
            elem_id = f"checkbox_{self.component_counter}"
            self.component_counter += 1
            lines.append(f"{prefix}<input type='checkbox' id='{elem_id}' class='neo-checkbox' />")

        elif tag == 'Box':
            lines.append(f"{prefix}<div class='neo-box'>")
            for child in element:
                lines.extend(self._generate_html_from_element(child, indent + 2))
            lines.append(f"{prefix}</div>")

        elif tag == 'Repeater':
            # Repeater será implementado com template + loop
            elem_id = f"repeater_{self.component_counter}"
            self.component_counter += 1
            lines.append(f"{prefix}<div id='{elem_id}' class='neo-repeater'>")
            lines.append(f"{prefix}  <!-- Repeater content will be dynamically generated -->")
            lines.append(f"{prefix}</div>")

        return lines

