// Generated by OpenFlex Neo
// AS4 -> JavaScript


// Polyfill for Node.js
const trace = typeof console !== 'undefined' ? console.log : () => {};

// OpenFlex Reactivity Runtime (inline for browser compatibility)
class Signal {
    constructor(initialValue) {
        this._value = initialValue;
        this._subscribers = [];
    }

    get value() {
        if (typeof currentEffect !== 'undefined' && currentEffect) {
            this._subscribers.push(currentEffect);
        }
        return this._value;
    }

    set value(newValue) {
        if (this._value !== newValue) {
            this._value = newValue;
            this._subscribers.forEach(effect => effect());
        }
    }
}

class Computed {
    constructor(fn) {
        this._fn = fn;
        this._value = undefined;
        this._dirty = true;
        this._subscribers = [];
    }

    get value() {
        if (this._dirty) {
            this._value = this._fn();
            this._dirty = false;
        }
        if (typeof currentEffect !== 'undefined' && currentEffect) {
            this._subscribers.push(currentEffect);
        }
        return this._value;
    }
}

let currentEffect = null;

function createEffect(fn) {
    currentEffect = fn;
    fn();
    currentEffect = null;
}

const count = new Signal(0);

const message = new Signal("Hello, OpenFlex!");

createEffect(() => logCount());
function logCount() {
  trace("Count changed: " + count.value);
}

createEffect(() => logMessage());
function logMessage() {
  trace("Message: " + message.value);
}

function increment() {
  count.value = count.value + 1;
}

function decrement() {
  count.value = count.value - 1;
}

function setMessage(msg) {
  message.value = msg;
}

trace("=== OpenFlex Neo Reactivity Demo ===");

trace("");

trace("Initial state:");

trace("");

trace("Incrementing count...");

increment();

trace("");

trace("Incrementing again...");

increment();

trace("");

trace("Decrementing...");

decrement();

trace("");

trace("Changing message...");

setMessage("Reactivity is awesome!");

trace("");

trace("✨ Reactivity working perfectly! ✨");
