// Generated by OpenFlex Neo
// AS4 -> JavaScript


// Polyfill for Node.js
const trace = typeof console !== 'undefined' ? console.log : () => {};
// OpenFlex Reactivity Runtime
const { Signal, Computed, createEffect } = require('./runtime/openflex-runtime.js');

const count = new Signal(0);

const message = new Signal("Hello, OpenFlex!");

createEffect(() => logCount());
function logCount() {
  trace("Count changed: " + count.value);
}

createEffect(() => logMessage());
function logMessage() {
  trace("Message: " + message.value);
}

function increment() {
  count.value = count.value + 1;
}

function decrement() {
  count.value = count.value - 1;
}

function setMessage(msg) {
  message.value = msg;
}

trace("=== OpenFlex Neo Reactivity Demo ===");

trace("");

trace("Initial state:");

trace("");

trace("Incrementing count...");

increment();

trace("");

trace("Incrementing again...");

increment();

trace("");

trace("Decrementing...");

decrement();

trace("");

trace("Changing message...");

setMessage("Reactivity is awesome!");

trace("");

trace("✨ Reactivity working perfectly! ✨");
