"""
JavaScript Code Generator for ActionScript 4 (OpenFlex Neo)

Generates JavaScript code from AS4 AST.
"""

from typing import List, Optional
from compiler.parser.ast import *


class JSCodeGenerator:
    """Generates JavaScript code from AS4 AST"""

    def __init__(self):
        self.indent_level = 0
        self.indent_str = "  "  # 2 spaces
        self.reactive_vars = set()  # Track reactive variables
        self.has_reactivity = False  # Track if we need runtime import
        self._current_class_properties = set()  # Track class property names for this. insertion
        self._in_class_method = False  # Track if we're generating a class method body
        self._method_local_names = set()  # Track method params and local vars (shadow this.)

    def generate(self, program: Program) -> str:
        """Generate JavaScript code for entire program"""
        lines = []

        # Add header comment
        lines.append("// Generated by OpenFlex Neo")
        lines.append("// AS4 -> JavaScript")
        lines.append("")

        # Scan for reactivity features
        self._scan_for_reactivity(program)

        # Add runtime import if needed
        if self.has_reactivity:
            lines.append("// OpenFlex Reactivity Runtime")
            lines.append("const { Signal, Computed, createEffect } = (typeof window !== 'undefined' && window.OpenFlexRuntime)")
            lines.append("  ? window.OpenFlexRuntime")
            lines.append("  : require('./runtime/openflex-runtime.js');")
            lines.append("")

        # Generate each declaration
        for decl in program.declarations:
            code = self._generate_statement(decl)
            if code:
                lines.append(code)
                lines.append("")  # Blank line between declarations

        return "\n".join(lines)

    def _scan_for_reactivity(self, program: Program):
        """Scan program for reactive features"""
        for decl in program.declarations:
            if isinstance(decl, VariableDeclaration):
                if any(d.name == 'reactive' for d in decl.decorators):
                    self.has_reactivity = True
                    self.reactive_vars.add(decl.name)
                elif any(d.name == 'computed' for d in decl.decorators):
                    self.has_reactivity = True
                    self.reactive_vars.add(decl.name)  # Computed vars are also reactive
            elif isinstance(decl, FunctionDeclaration):
                if any(d.name in ('computed', 'effect') for d in decl.decorators):
                    self.has_reactivity = True

    def _generate_statement(self, stmt: Statement) -> str:
        """Generate code for a statement"""
        if isinstance(stmt, VariableDeclaration):
            return self._generate_variable_declaration(stmt)
        elif isinstance(stmt, DestructuringDeclaration):
            return self._generate_destructuring_declaration(stmt)
        elif isinstance(stmt, FunctionDeclaration):
            return self._generate_function_declaration(stmt)
        elif isinstance(stmt, ClassDeclaration):
            return self._generate_class_declaration(stmt)
        elif isinstance(stmt, ReturnStatement):
            return self._generate_return_statement(stmt)
        elif isinstance(stmt, ExpressionStatement):
            return self._generate_expression_statement(stmt)
        elif isinstance(stmt, BlockStatement):
            return self._generate_block_statement(stmt)
        elif isinstance(stmt, IfStatement):
            return self._generate_if_statement(stmt)
        elif isinstance(stmt, ForStatement):
            return self._generate_for_statement(stmt)
        elif isinstance(stmt, ForInStatement):
            return self._generate_for_in_statement(stmt)
        elif isinstance(stmt, ForOfStatement):
            return self._generate_for_of_statement(stmt)
        elif isinstance(stmt, WhileStatement):
            return self._generate_while_statement(stmt)
        elif isinstance(stmt, TryStatement):
            return self._generate_try_statement(stmt)
        elif isinstance(stmt, ThrowStatement):
            return self._generate_throw_statement(stmt)
        elif isinstance(stmt, BreakStatement):
            return self._generate_break_statement(stmt)
        elif isinstance(stmt, ContinueStatement):
            return self._generate_continue_statement(stmt)
        elif isinstance(stmt, ImportDeclaration):
            return self._generate_import_declaration(stmt)
        else:
            return f"/* TODO: {stmt.__class__.__name__} */"

    def _generate_variable_declaration(self, var_decl: VariableDeclaration) -> str:
        """Generate variable declaration"""
        # Track local variable names inside class methods to avoid this. insertion
        if self._in_class_method:
            self._method_local_names.add(var_decl.name)

        # Check for decorators
        is_reactive = any(d.name == 'reactive' for d in var_decl.decorators)
        is_computed = any(d.name == 'computed' for d in var_decl.decorators)

        # Reactive/computed variables are always const (the Signal/Computed is const)
        keyword = "const" if (var_decl.is_const or is_reactive or is_computed) else "let"
        name = var_decl.name

        if var_decl.initializer:
            value = self._generate_expression(var_decl.initializer)

            if is_reactive:
                # Wrap in Signal
                return f"{self._indent()}{keyword} {name} = new Signal({value});"
            elif is_computed:
                # Wrap in Computed
                # Check if initializer is a BlockStatement (from @computed var x: T { ... })
                from compiler.parser.ast import ArrowFunction, BlockStatement
                if isinstance(var_decl.initializer, BlockStatement):
                    # Block from computed_variable_declaration - convert to arrow function
                    block_code = self._generate_block_statement(var_decl.initializer)
                    return f"{self._indent()}{keyword} {name} = new Computed(() => {block_code});"
                elif isinstance(var_decl.initializer, ArrowFunction):
                    # Already an arrow function, just use it directly
                    return f"{self._indent()}{keyword} {name} = new Computed({value});"
                else:
                    # Wrap in arrow function
                    return f"{self._indent()}{keyword} {name} = new Computed(() => {value});"
            else:
                return f"{self._indent()}{keyword} {name} = {value};"
        else:
            if is_reactive:
                # Reactive variable without initializer defaults to undefined
                return f"{self._indent()}{keyword} {name} = new Signal(undefined);"
            elif is_computed:
                # Computed must have an expression
                return f"{self._indent()}{keyword} {name} = new Computed(() => undefined);"
            else:
                return f"{self._indent()}{keyword} {name};"

    def _generate_destructuring_declaration(self, destruct_decl: DestructuringDeclaration) -> str:
        """Generate destructuring declaration"""
        keyword = "const" if destruct_decl.is_const else "let"
        pattern = self._generate_destructuring_pattern(destruct_decl.pattern)

        if destruct_decl.initializer:
            value = self._generate_expression(destruct_decl.initializer)
            return f"{self._indent()}{keyword} {pattern} = {value};"
        else:
            return f"{self._indent()}{keyword} {pattern};"

    def _generate_destructuring_pattern(self, pattern: Pattern) -> str:
        """Generate destructuring pattern code"""
        if isinstance(pattern, IdentifierPattern):
            return pattern.name
        elif isinstance(pattern, WildcardPattern):
            return ""  # Empty slot in array destructuring
        elif isinstance(pattern, ArrayPattern):
            return self._generate_array_pattern(pattern)
        elif isinstance(pattern, ObjectPattern):
            return self._generate_object_pattern(pattern)
        else:
            return f"/* TODO: Pattern {pattern.__class__.__name__} */"

    def _generate_array_pattern(self, pattern: ArrayPattern) -> str:
        """Generate array destructuring pattern: [a, b, ...rest]"""
        elements = []

        for elem in pattern.elements:
            elem_str = self._generate_destructuring_pattern(elem)
            elements.append(elem_str)

        # Add rest element if present
        if pattern.rest:
            elements.append(f"...{pattern.rest}")

        return f"[{', '.join(elements)}]"

    def _generate_object_pattern(self, pattern: ObjectPattern) -> str:
        """Generate object destructuring pattern: {x, y: newY, ...rest}"""
        props = []

        for key, value_pattern in pattern.properties.items():
            if isinstance(value_pattern, IdentifierPattern) and value_pattern.name == key:
                # Shorthand: {x} instead of {x: x}
                props.append(key)
            elif isinstance(value_pattern, IdentifierPattern):
                # Rename: {name: n}
                props.append(f"{key}: {value_pattern.name}")
            else:
                # Nested pattern: {pos: {x, y}}
                nested = self._generate_destructuring_pattern(value_pattern)
                props.append(f"{key}: {nested}")

        # Add rest property if present
        if pattern.rest:
            props.append(f"...{pattern.rest}")

        return f"{{{', '.join(props)}}}"

    def _generate_function_declaration(self, func_decl: FunctionDeclaration) -> str:
        """Generate function declaration"""
        name = func_decl.name

        # Check for @effect decorator
        is_effect = any(d.name == 'effect' for d in func_decl.decorators)

        # Async modifier
        async_keyword = "async " if func_decl.is_async else ""

        # Parameters
        params = []
        for param in func_decl.params:
            param_name = param.name
            prefix = "..." if param.is_rest else ""
            if param.default_value:
                default = self._generate_expression(param.default_value)
                params.append(f"{prefix}{param_name} = {default}")
            else:
                params.append(f"{prefix}{param_name}")

        params_str = ", ".join(params)

        # Body
        if func_decl.body:
            body = self._generate_block_statement(func_decl.body)

            if is_effect:
                # Wrap in createEffect
                return f"{self._indent()}createEffect(() => {name}({params_str}));\n{self._indent()}{async_keyword}function {name}({params_str}) {body}"
            else:
                return f"{self._indent()}{async_keyword}function {name}({params_str}) {body}"
        else:
            if is_effect:
                return f"{self._indent()}createEffect(() => {name}({params_str}));\n{self._indent()}function {name}({params_str}) {{}}"
            else:
                return f"{self._indent()}function {name}({params_str}) {{}}"

    def _generate_class_declaration(self, class_decl: ClassDeclaration) -> str:
        """Generate class declaration"""
        name = class_decl.name
        lines = []

        # Collect all property names for this. insertion in methods
        class_properties = set()
        for member in class_decl.members:
            if isinstance(member, PropertyDeclaration):
                class_properties.add(member.name)
            elif isinstance(member, VariableDeclaration):
                class_properties.add(member.name)

        # Class header
        if class_decl.super_class:
            super_name = class_decl.super_class.name
            lines.append(f"{self._indent()}class {name} extends {super_name} {{")
        else:
            lines.append(f"{self._indent()}class {name} {{")

        self.indent_level += 1

        # Generate members
        for member in class_decl.members:
            if isinstance(member, PropertyDeclaration):
                # Property
                static_prefix = "static " if member.is_static else ""
                prop_name = member.name
                if member.initializer:
                    value = self._generate_expression(member.initializer)
                    lines.append(f"{self._indent()}{static_prefix}{prop_name} = {value};")
                else:
                    lines.append(f"{self._indent()}{static_prefix}{prop_name};")

            elif isinstance(member, VariableDeclaration):
                # Variable declaration (treated as property in classes)
                static_prefix = "static " if member.is_static else ""
                prop_name = member.name
                if member.initializer:
                    value = self._generate_expression(member.initializer)
                    lines.append(f"{self._indent()}{static_prefix}{prop_name} = {value};")
                else:
                    lines.append(f"{self._indent()}{static_prefix}{prop_name};")

            elif isinstance(member, FunctionDeclaration):
                # Method - set class context for this. insertion
                prev_props = self._current_class_properties
                prev_in_method = self._in_class_method
                prev_locals = self._method_local_names
                self._current_class_properties = class_properties
                self._in_class_method = True
                # Collect parameter names so they shadow class properties
                self._method_local_names = {p.name for p in member.params}

                # Build method signature directly (not via _generate_function_declaration)
                static_prefix = "static " if member.is_static else ""
                async_prefix = "async " if member.is_async else ""
                method_name = member.name

                # Parameters with rest support
                params = []
                for param in member.params:
                    param_name = param.name
                    prefix = "..." if param.is_rest else ""
                    if param.default_value:
                        default = self._generate_expression(param.default_value)
                        params.append(f"{prefix}{param_name} = {default}")
                    else:
                        params.append(f"{prefix}{param_name}")
                params_str = ", ".join(params)

                # Body
                if member.body:
                    body = self._generate_block_statement(member.body)
                else:
                    body = "{}"

                lines.append(f"{self._indent()}{static_prefix}{async_prefix}{method_name}({params_str}) {body}")

                # Restore context
                self._current_class_properties = prev_props
                self._in_class_method = prev_in_method
                self._method_local_names = prev_locals

        self.indent_level -= 1
        lines.append(f"{self._indent()}}}")

        return "\n".join(lines)

    def _generate_return_statement(self, ret_stmt: ReturnStatement) -> str:
        """Generate return statement"""
        if ret_stmt.argument:
            arg = self._generate_expression(ret_stmt.argument)
            return f"{self._indent()}return {arg};"
        else:
            return f"{self._indent()}return;"

    def _generate_expression_statement(self, expr_stmt: ExpressionStatement) -> str:
        """Generate expression statement"""
        expr = self._generate_expression(expr_stmt.expression)
        return f"{self._indent()}{expr};"

    def _generate_block_statement(self, block_stmt: BlockStatement) -> str:
        """Generate block statement"""
        if not block_stmt.body:
            return "{}"

        lines = ["{"]
        self.indent_level += 1

        for stmt in block_stmt.body:
            code = self._generate_statement(stmt)
            if code:
                lines.append(code)

        self.indent_level -= 1
        lines.append(f"{self._indent()}}}")

        return "\n".join(lines)

    def _generate_if_statement(self, if_stmt: IfStatement) -> str:
        """Generate if statement"""
        test = self._generate_expression(if_stmt.test)
        consequent = self._generate_statement(if_stmt.consequent)

        lines = [f"{self._indent()}if ({test}) {consequent}"]

        if if_stmt.alternate:
            alternate = self._generate_statement(if_stmt.alternate)
            lines.append(f"{self._indent()}else {alternate}")

        return "\n".join(lines)

    def _generate_for_statement(self, for_stmt: ForStatement) -> str:
        """Generate for statement"""
        # Init
        if for_stmt.init:
            if isinstance(for_stmt.init, VariableDeclaration):
                # Strip semicolon and indent from variable declaration
                init = self._generate_variable_declaration(for_stmt.init).strip().rstrip(';')
                # Remove indent and keyword prefix for inline for loop
                init = init.lstrip()
            else:
                init = self._generate_expression(for_stmt.init)
        else:
            init = ""

        # Test
        test = self._generate_expression(for_stmt.test) if for_stmt.test else ""

        # Update
        update = self._generate_expression(for_stmt.update) if for_stmt.update else ""

        # Body
        body = self._generate_statement(for_stmt.body)

        return f"{self._indent()}for ({init}; {test}; {update}) {body}"

    def _generate_while_statement(self, while_stmt: WhileStatement) -> str:
        """Generate while statement"""
        test = self._generate_expression(while_stmt.test)
        body = self._generate_statement(while_stmt.body)

        return f"{self._indent()}while ({test}) {body}"

    def _generate_expression(self, expr: Expression) -> str:
        """Generate code for an expression"""
        if isinstance(expr, Literal):
            return self._generate_literal(expr)
        elif isinstance(expr, Identifier):
            # Auto-transform reactive variable access
            if expr.name in self.reactive_vars:
                return f"{expr.name}.value"
            # Add this. prefix for class property references inside methods
            # but not for local names (parameters, local vars) that shadow them
            if self._in_class_method and expr.name in self._current_class_properties and expr.name not in self._method_local_names:
                return f"this.{expr.name}"
            return expr.name
        elif isinstance(expr, BinaryExpression):
            return self._generate_binary_expression(expr)
        elif isinstance(expr, UnaryExpression):
            return self._generate_unary_expression(expr)
        elif isinstance(expr, CallExpression):
            return self._generate_call_expression(expr)
        elif isinstance(expr, OptionalCallExpression):
            return self._generate_optional_call_expression(expr)
        elif isinstance(expr, MemberExpression):
            return self._generate_member_expression(expr)
        elif isinstance(expr, OptionalMemberExpression):
            return self._generate_optional_member_expression(expr)
        elif isinstance(expr, ArrayLiteral):
            return self._generate_array_literal(expr)
        elif isinstance(expr, ObjectLiteral):
            return self._generate_object_literal(expr)
        elif isinstance(expr, ConditionalExpression):
            return self._generate_conditional_expression(expr)
        elif isinstance(expr, AwaitExpression):
            return self._generate_await_expression(expr)
        elif isinstance(expr, ArrowFunction):
            return self._generate_arrow_function(expr)
        elif isinstance(expr, NewExpression):
            return self._generate_new_expression(expr)
        elif isinstance(expr, TemplateString):
            return self._generate_template_string(expr)
        else:
            return f"/* TODO: {expr.__class__.__name__} */"

    def _generate_literal(self, literal: Literal) -> str:
        """Generate literal value"""
        if isinstance(literal, NumberLiteral):
            # Format integers without decimal point
            if isinstance(literal.value, float) and literal.value.is_integer():
                return str(int(literal.value))
            return str(literal.value)
        elif isinstance(literal, StringLiteral):
            # Use raw if available for correct escaping
            if hasattr(literal, 'raw') and literal.raw:
                return literal.raw
            # Escape special characters when raw is not available
            escaped = literal.value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
            return f'"{escaped}"'
        elif isinstance(literal, BooleanLiteral):
            return "true" if literal.value else "false"
        elif isinstance(literal, NullLiteral):
            return "null"
        elif hasattr(literal, 'pattern'):  # RegexLiteral
            # Return the pattern as-is (already includes /pattern/flags format)
            return literal.pattern
        else:
            return str(literal.value)

    # Operator precedence table (higher number = higher precedence)
    _PRECEDENCE = {
        '=': 1, '+=': 1, '-=': 1, '*=': 1, '/=': 1, '%=': 1, '**=': 1,
        '??': 2,
        '||': 3,
        '&&': 4,
        '|': 5,
        '^': 6,
        '&': 7,
        '==': 8, '!=': 8, '===': 8, '!==': 8,
        '<': 9, '>': 9, '<=': 9, '>=': 9, 'instanceof': 9, 'in': 9,
        '<<': 10, '>>': 10, '>>>': 10,
        '+': 11, '-': 11,
        '*': 12, '/': 12, '%': 12,
        '**': 13,
    }

    def _generate_binary_expression(self, binary: BinaryExpression) -> str:
        """Generate binary expression with proper precedence"""
        left = self._generate_expression(binary.left)
        right = self._generate_expression(binary.right)

        # Add parentheses around child binary expressions with lower precedence
        my_prec = self._PRECEDENCE.get(binary.operator, 11)

        if isinstance(binary.left, BinaryExpression):
            left_prec = self._PRECEDENCE.get(binary.left.operator, 11)
            if left_prec < my_prec:
                left = f"({left})"

        if isinstance(binary.right, BinaryExpression):
            right_prec = self._PRECEDENCE.get(binary.right.operator, 11)
            if right_prec <= my_prec:
                right = f"({right})"

        return f"{left} {binary.operator} {right}"

    def _generate_unary_expression(self, unary: UnaryExpression) -> str:
        """Generate unary expression"""
        arg = self._generate_expression(unary.operand)
        if unary.is_prefix:
            return f"{unary.operator}{arg}"
        else:
            return f"{arg}{unary.operator}"

    def _generate_call_expression(self, call: CallExpression) -> str:
        """Generate function call"""
        callee = self._generate_expression(call.callee)
        args = [self._generate_expression(arg) for arg in call.arguments]
        args_str = ", ".join(args)
        return f"{callee}({args_str})"

    def _generate_member_expression(self, member: MemberExpression) -> str:
        """Generate member access"""
        obj = self._generate_expression(member.object)

        # For non-computed member access (obj.prop), generate property name directly
        # without going through _generate_expression to avoid adding .value
        if member.is_computed:
            prop = self._generate_expression(member.property)
            return f"{obj}[{prop}]"
        else:
            # For obj.prop, just get the property name without transformation
            from compiler.parser.ast import Identifier
            if isinstance(member.property, Identifier):
                prop = member.property.name
            else:
                prop = self._generate_expression(member.property)
            return f"{obj}.{prop}"

    def _generate_optional_member_expression(self, member: OptionalMemberExpression) -> str:
        """Generate optional member access: obj?.prop or obj?.[key]"""
        obj = self._generate_expression(member.object)

        # For non-computed member access (obj?.prop), generate property name directly
        if member.is_computed:
            prop = self._generate_expression(member.property)
            return f"{obj}?.[{prop}]"
        else:
            from compiler.parser.ast import Identifier
            if isinstance(member.property, Identifier):
                prop = member.property.name
            else:
                prop = self._generate_expression(member.property)
            return f"{obj}?.{prop}"

    def _generate_optional_call_expression(self, call: OptionalCallExpression) -> str:
        """Generate optional function call: func?.()"""
        callee = self._generate_expression(call.callee)
        args = [self._generate_expression(arg) for arg in call.arguments]
        args_str = ", ".join(args)
        return f"{callee}?.({args_str})"

    def _generate_array_literal(self, array: ArrayLiteral) -> str:
        """Generate array literal with spread support"""
        from ..parser.ast import SpreadElement
        elements = []
        for elem in array.elements:
            if isinstance(elem, SpreadElement):
                elements.append(f"...{self._generate_expression(elem.argument)}")
            else:
                elements.append(self._generate_expression(elem))
        elements_str = ", ".join(elements)
        return f"[{elements_str}]"

    def _generate_object_literal(self, obj: ObjectLiteral) -> str:
        """Generate object literal with spread support"""
        from ..parser.ast import SpreadElement
        if not obj.properties:
            return "{}"

        props = []
        for prop in obj.properties:
            if isinstance(prop, SpreadElement):
                # Spread in object: {...obj}
                props.append(f"...{self._generate_expression(prop.argument)}")
            else:
                key = prop.key.name if isinstance(prop.key, Identifier) else self._generate_expression(prop.key)
                value = self._generate_expression(prop.value)
                props.append(f"{key}: {value}")

        props_str = ", ".join(props)
        return f"{{ {props_str} }}"

    def _generate_conditional_expression(self, cond: ConditionalExpression) -> str:
        """Generate ternary expression"""
        test = self._generate_expression(cond.test)
        consequent = self._generate_expression(cond.consequent)
        alternate = self._generate_expression(cond.alternate)
        # Always wrap ternary in parentheses to preserve precedence
        # This ensures (a ? b : c) + d works correctly
        return f"({test} ? {consequent} : {alternate})"

    def _generate_await_expression(self, await_expr: AwaitExpression) -> str:
        """Generate await expression"""
        argument = self._generate_expression(await_expr.argument)
        return f"await {argument}"

    def _generate_arrow_function(self, arrow: ArrowFunction) -> str:
        """Generate arrow function"""
        # Async modifier
        async_keyword = "async " if arrow.is_async else ""

        # Parameters
        if len(arrow.params) == 1 and not arrow.params[0].default_value and not arrow.params[0].is_rest:
            # Single parameter without default and not rest - no parentheses needed
            params_str = arrow.params[0].name
        else:
            params = []
            for param in arrow.params:
                param_name = param.name
                prefix = "..." if param.is_rest else ""
                if param.default_value:
                    default = self._generate_expression(param.default_value)
                    params.append(f"{prefix}{param_name} = {default}")
                else:
                    params.append(f"{prefix}{param_name}")
            params_str = f"({', '.join(params)})"

        # Body
        if isinstance(arrow.body, BlockStatement):
            # Block body
            body_str = self._generate_block_statement(arrow.body)
            return f"{async_keyword}{params_str} => {body_str}"
        else:
            # Expression body
            body_str = self._generate_expression(arrow.body)
            # Wrap object literals in parentheses to avoid ambiguity
            if isinstance(arrow.body, ObjectLiteral):
                return f"{async_keyword}{params_str} => ({body_str})"
            return f"{async_keyword}{params_str} => {body_str}"

    def _generate_new_expression(self, new_expr: NewExpression) -> str:
        """Generate new expression"""
        callee = self._generate_expression(new_expr.callee)
        args = [self._generate_expression(arg) for arg in new_expr.arguments]
        args_str = ", ".join(args)
        return f"new {callee}({args_str})"

    def _generate_for_in_statement(self, stmt: ForInStatement) -> str:
        """Generate for-in statement: for (key in obj)"""
        if isinstance(stmt.left, VariableDeclaration):
            keyword = "const" if stmt.left.is_const else "let"
            left = f"{keyword} {stmt.left.name}"
        else:
            left = self._generate_expression(stmt.left)
        right = self._generate_expression(stmt.right)
        body = self._generate_statement(stmt.body)
        return f"{self._indent()}for ({left} in {right}) {body}"

    def _generate_for_of_statement(self, stmt: ForOfStatement) -> str:
        """Generate for-of statement: for (item of array)"""
        if isinstance(stmt.left, VariableDeclaration):
            keyword = "const" if stmt.left.is_const else "let"
            left = f"{keyword} {stmt.left.name}"
        else:
            left = self._generate_expression(stmt.left)
        right = self._generate_expression(stmt.right)
        body = self._generate_statement(stmt.body)
        return f"{self._indent()}for ({left} of {right}) {body}"

    def _generate_try_statement(self, stmt: TryStatement) -> str:
        """Generate try-catch-finally statement"""
        lines = []
        block = self._generate_block_statement(stmt.block)
        lines.append(f"{self._indent()}try {block}")

        if stmt.handler:
            if stmt.handler.param:
                catch_body = self._generate_block_statement(stmt.handler.body)
                lines.append(f"{self._indent()}catch ({stmt.handler.param}) {catch_body}")
            else:
                catch_body = self._generate_block_statement(stmt.handler.body)
                lines.append(f"{self._indent()}catch {catch_body}")

        if stmt.finalizer:
            finally_body = self._generate_block_statement(stmt.finalizer)
            lines.append(f"{self._indent()}finally {finally_body}")

        return "\n".join(lines)

    def _generate_throw_statement(self, stmt: ThrowStatement) -> str:
        """Generate throw statement"""
        arg = self._generate_expression(stmt.argument)
        return f"{self._indent()}throw {arg};"

    def _generate_break_statement(self, stmt: BreakStatement) -> str:
        """Generate break statement"""
        if stmt.label:
            return f"{self._indent()}break {stmt.label};"
        return f"{self._indent()}break;"

    def _generate_continue_statement(self, stmt: ContinueStatement) -> str:
        """Generate continue statement"""
        if stmt.label:
            return f"{self._indent()}continue {stmt.label};"
        return f"{self._indent()}continue;"

    def _generate_import_declaration(self, stmt: ImportDeclaration) -> str:
        """Generate import declaration"""
        if not stmt.specifiers:
            return f'{self._indent()}import "{stmt.source}";'

        specifiers = []
        default_specifier = None
        for spec in stmt.specifiers:
            if spec.imported == 'default':
                default_specifier = spec.local
            elif spec.imported == spec.local:
                specifiers.append(spec.local)
            else:
                specifiers.append(f"{spec.imported} as {spec.local}")

        parts = []
        if default_specifier:
            parts.append(default_specifier)
        if specifiers:
            parts.append(f"{{ {', '.join(specifiers)} }}")

        return f'{self._indent()}import {", ".join(parts)} from "{stmt.source}";'

    def _generate_template_string(self, template: TemplateString) -> str:
        """Generate template string: `Hello ${name}`"""
        result = "`"
        for part in template.parts:
            if isinstance(part, StringLiteral):
                # Raw text part - escape backticks only
                text = part.value.replace('`', '\\`')
                result += text
            else:
                # Expression part
                expr = self._generate_expression(part)
                result += f"${{{expr}}}"
        result += "`"
        return result

    def _indent(self) -> str:
        """Get current indentation"""
        return self.indent_str * self.indent_level
