"""
JavaScript Code Generator for ActionScript 4 (OpenFlex Neo)

Generates JavaScript code from AS4 AST.
"""

from typing import List, Optional
from compiler.parser.ast import *


class JSCodeGenerator:
    """Generates JavaScript code from AS4 AST"""

    def __init__(self):
        self.indent_level = 0
        self.indent_str = "  "  # 2 spaces

    def generate(self, program: Program) -> str:
        """Generate JavaScript code for entire program"""
        lines = []

        # Add header comment
        lines.append("// Generated by OpenFlex Neo")
        lines.append("// AS4 -> JavaScript")
        lines.append("")

        # Generate each declaration
        for decl in program.declarations:
            code = self._generate_statement(decl)
            if code:
                lines.append(code)
                lines.append("")  # Blank line between declarations

        return "\n".join(lines)

    def _generate_statement(self, stmt: Statement) -> str:
        """Generate code for a statement"""
        if isinstance(stmt, VariableDeclaration):
            return self._generate_variable_declaration(stmt)
        elif isinstance(stmt, FunctionDeclaration):
            return self._generate_function_declaration(stmt)
        elif isinstance(stmt, ClassDeclaration):
            return self._generate_class_declaration(stmt)
        elif isinstance(stmt, ReturnStatement):
            return self._generate_return_statement(stmt)
        elif isinstance(stmt, ExpressionStatement):
            return self._generate_expression_statement(stmt)
        elif isinstance(stmt, BlockStatement):
            return self._generate_block_statement(stmt)
        elif isinstance(stmt, IfStatement):
            return self._generate_if_statement(stmt)
        elif isinstance(stmt, ForStatement):
            return self._generate_for_statement(stmt)
        elif isinstance(stmt, WhileStatement):
            return self._generate_while_statement(stmt)
        else:
            return f"/* TODO: {stmt.__class__.__name__} */"

    def _generate_variable_declaration(self, var_decl: VariableDeclaration) -> str:
        """Generate variable declaration"""
        keyword = "const" if var_decl.is_const else "let"
        name = var_decl.name

        if var_decl.initializer:
            value = self._generate_expression(var_decl.initializer)
            return f"{self._indent()}{keyword} {name} = {value};"
        else:
            return f"{self._indent()}{keyword} {name};"

    def _generate_function_declaration(self, func_decl: FunctionDeclaration) -> str:
        """Generate function declaration"""
        name = func_decl.name

        # Parameters
        params = []
        for param in func_decl.params:
            param_name = param.name
            if param.default_value:
                default = self._generate_expression(param.default_value)
                params.append(f"{param_name} = {default}")
            else:
                params.append(param_name)

        params_str = ", ".join(params)

        # Body
        if func_decl.body:
            body = self._generate_block_statement(func_decl.body)
            return f"{self._indent()}function {name}({params_str}) {body}"
        else:
            return f"{self._indent()}function {name}({params_str}) {{}}"

    def _generate_class_declaration(self, class_decl: ClassDeclaration) -> str:
        """Generate class declaration"""
        name = class_decl.name
        lines = []

        # Class header
        if class_decl.super_class:
            super_name = class_decl.super_class.name
            lines.append(f"{self._indent()}class {name} extends {super_name} {{")
        else:
            lines.append(f"{self._indent()}class {name} {{")

        self.indent_level += 1

        # Generate members
        for member in class_decl.members:
            if isinstance(member, PropertyDeclaration):
                # Property
                prop_name = member.name
                if member.initializer:
                    value = self._generate_expression(member.initializer)
                    lines.append(f"{self._indent()}{prop_name} = {value};")
                else:
                    lines.append(f"{self._indent()}{prop_name};")

            elif isinstance(member, VariableDeclaration):
                # Variable declaration (treated as property in classes)
                prop_name = member.name
                if member.initializer:
                    value = self._generate_expression(member.initializer)
                    lines.append(f"{self._indent()}{prop_name} = {value};")
                else:
                    lines.append(f"{self._indent()}{prop_name};")

            elif isinstance(member, FunctionDeclaration):
                # Method
                method_code = self._generate_function_declaration(member)
                # Remove 'function' keyword for class methods
                method_code = method_code.replace("function ", "")
                lines.append(method_code)

        self.indent_level -= 1
        lines.append(f"{self._indent()}}}")

        return "\n".join(lines)

    def _generate_return_statement(self, ret_stmt: ReturnStatement) -> str:
        """Generate return statement"""
        if ret_stmt.argument:
            arg = self._generate_expression(ret_stmt.argument)
            return f"{self._indent()}return {arg};"
        else:
            return f"{self._indent()}return;"

    def _generate_expression_statement(self, expr_stmt: ExpressionStatement) -> str:
        """Generate expression statement"""
        expr = self._generate_expression(expr_stmt.expression)
        return f"{self._indent()}{expr};"

    def _generate_block_statement(self, block_stmt: BlockStatement) -> str:
        """Generate block statement"""
        if not block_stmt.body:
            return "{}"

        lines = ["{"]
        self.indent_level += 1

        for stmt in block_stmt.body:
            code = self._generate_statement(stmt)
            if code:
                lines.append(code)

        self.indent_level -= 1
        lines.append(f"{self._indent()}}}")

        return "\n".join(lines)

    def _generate_if_statement(self, if_stmt: IfStatement) -> str:
        """Generate if statement"""
        test = self._generate_expression(if_stmt.test)
        consequent = self._generate_statement(if_stmt.consequent)

        lines = [f"{self._indent()}if ({test}) {consequent}"]

        if if_stmt.alternate:
            alternate = self._generate_statement(if_stmt.alternate)
            lines.append(f"{self._indent()}else {alternate}")

        return "\n".join(lines)

    def _generate_for_statement(self, for_stmt: ForStatement) -> str:
        """Generate for statement"""
        # Init
        if for_stmt.init:
            if isinstance(for_stmt.init, VariableDeclaration):
                # Strip semicolon and indent from variable declaration
                init = self._generate_variable_declaration(for_stmt.init).strip().rstrip(';')
                # Remove indent and keyword prefix for inline for loop
                init = init.lstrip()
            else:
                init = self._generate_expression(for_stmt.init)
        else:
            init = ""

        # Test
        test = self._generate_expression(for_stmt.test) if for_stmt.test else ""

        # Update
        update = self._generate_expression(for_stmt.update) if for_stmt.update else ""

        # Body
        body = self._generate_statement(for_stmt.body)

        return f"{self._indent()}for ({init}; {test}; {update}) {body}"

    def _generate_while_statement(self, while_stmt: WhileStatement) -> str:
        """Generate while statement"""
        test = self._generate_expression(while_stmt.test)
        body = self._generate_statement(while_stmt.body)

        return f"{self._indent()}while ({test}) {body}"

    def _generate_expression(self, expr: Expression) -> str:
        """Generate code for an expression"""
        if isinstance(expr, Literal):
            return self._generate_literal(expr)
        elif isinstance(expr, Identifier):
            return expr.name
        elif isinstance(expr, BinaryExpression):
            return self._generate_binary_expression(expr)
        elif isinstance(expr, UnaryExpression):
            return self._generate_unary_expression(expr)
        elif isinstance(expr, CallExpression):
            return self._generate_call_expression(expr)
        elif isinstance(expr, MemberExpression):
            return self._generate_member_expression(expr)
        elif isinstance(expr, ArrayLiteral):
            return self._generate_array_literal(expr)
        elif isinstance(expr, ObjectLiteral):
            return self._generate_object_literal(expr)
        elif isinstance(expr, ConditionalExpression):
            return self._generate_conditional_expression(expr)
        else:
            return f"/* TODO: {expr.__class__.__name__} */"

    def _generate_literal(self, literal: Literal) -> str:
        """Generate literal value"""
        if isinstance(literal, NumberLiteral):
            # Format integers without decimal point
            if isinstance(literal.value, float) and literal.value.is_integer():
                return str(int(literal.value))
            return str(literal.value)
        elif isinstance(literal, StringLiteral):
            # Use raw if available for correct escaping
            if hasattr(literal, 'raw') and literal.raw:
                return literal.raw
            return f'"{literal.value}"'
        elif isinstance(literal, BooleanLiteral):
            return "true" if literal.value else "false"
        elif isinstance(literal, NullLiteral):
            return "null"
        else:
            return str(literal.value)

    def _generate_binary_expression(self, binary: BinaryExpression) -> str:
        """Generate binary expression"""
        left = self._generate_expression(binary.left)
        right = self._generate_expression(binary.right)

        # Only add parentheses for complex expressions
        # Simple operators don't need wrapping
        if binary.operator in ['=', '==', '!=', '===', '!==', '<', '>', '<=', '>=', '&&', '||']:
            return f"{left} {binary.operator} {right}"
        else:
            # Arithmetic operators - add parentheses only if needed
            return f"{left} {binary.operator} {right}"

    def _generate_unary_expression(self, unary: UnaryExpression) -> str:
        """Generate unary expression"""
        arg = self._generate_expression(unary.operand)
        if unary.is_prefix:
            return f"{unary.operator}{arg}"
        else:
            return f"{arg}{unary.operator}"

    def _generate_call_expression(self, call: CallExpression) -> str:
        """Generate function call"""
        callee = self._generate_expression(call.callee)
        args = [self._generate_expression(arg) for arg in call.arguments]
        args_str = ", ".join(args)
        return f"{callee}({args_str})"

    def _generate_member_expression(self, member: MemberExpression) -> str:
        """Generate member access"""
        obj = self._generate_expression(member.object)
        prop = self._generate_expression(member.property)

        if member.computed:
            return f"{obj}[{prop}]"
        else:
            return f"{obj}.{prop}"

    def _generate_array_literal(self, array: ArrayLiteral) -> str:
        """Generate array literal"""
        elements = [self._generate_expression(elem) for elem in array.elements]
        elements_str = ", ".join(elements)
        return f"[{elements_str}]"

    def _generate_object_literal(self, obj: ObjectLiteral) -> str:
        """Generate object literal"""
        if not obj.properties:
            return "{}"

        props = []
        for prop in obj.properties:
            key = prop.key.name if isinstance(prop.key, Identifier) else self._generate_expression(prop.key)
            value = self._generate_expression(prop.value)
            props.append(f"{key}: {value}")

        props_str = ", ".join(props)
        return f"{{ {props_str} }}"

    def _generate_conditional_expression(self, cond: ConditionalExpression) -> str:
        """Generate ternary expression"""
        test = self._generate_expression(cond.test)
        consequent = self._generate_expression(cond.consequent)
        alternate = self._generate_expression(cond.alternate)
        return f"{test} ? {consequent} : {alternate}"

    def _indent(self) -> str:
        """Get current indentation"""
        return self.indent_str * self.indent_level
